#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradosCRUD.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parcial2_Progra5")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertgrado(grado instance);
    partial void Updategrado(grado instance);
    partial void Deletegrado(grado instance);
    partial void Insertdetalle_pensum(detalle_pensum instance);
    partial void Updatedetalle_pensum(detalle_pensum instance);
    partial void Deletedetalle_pensum(detalle_pensum instance);
    partial void Insertpensum(pensum instance);
    partial void Updatepensum(pensum instance);
    partial void Deletepensum(pensum instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<grado> grados
		{
			get
			{
				return this.GetTable<grado>();
			}
		}
		
		public System.Data.Linq.Table<detalle_pensum> detalle_pensums
		{
			get
			{
				return this.GetTable<detalle_pensum>();
			}
		}
		
		public System.Data.Linq.Table<pensum> pensums
		{
			get
			{
				return this.GetTable<pensum>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grado")]
	public partial class grado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_grado;
		
		private string _Nom_grado;
		
		private bool _estado_grado;
		
		private EntitySet<pensum> _pensums;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_gradoChanging(int value);
    partial void OnID_gradoChanged();
    partial void OnNom_gradoChanging(string value);
    partial void OnNom_gradoChanged();
    partial void Onestado_gradoChanging(bool value);
    partial void Onestado_gradoChanged();
    #endregion
		
		public grado()
		{
			this._pensums = new EntitySet<pensum>(new Action<pensum>(this.attach_pensums), new Action<pensum>(this.detach_pensums));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_grado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_grado
		{
			get
			{
				return this._ID_grado;
			}
			set
			{
				if ((this._ID_grado != value))
				{
					this.OnID_gradoChanging(value);
					this.SendPropertyChanging();
					this._ID_grado = value;
					this.SendPropertyChanged("ID_grado");
					this.OnID_gradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_grado", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom_grado
		{
			get
			{
				return this._Nom_grado;
			}
			set
			{
				if ((this._Nom_grado != value))
				{
					this.OnNom_gradoChanging(value);
					this.SendPropertyChanging();
					this._Nom_grado = value;
					this.SendPropertyChanged("Nom_grado");
					this.OnNom_gradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_grado", DbType="Bit NOT NULL")]
		public bool estado_grado
		{
			get
			{
				return this._estado_grado;
			}
			set
			{
				if ((this._estado_grado != value))
				{
					this.Onestado_gradoChanging(value);
					this.SendPropertyChanging();
					this._estado_grado = value;
					this.SendPropertyChanged("estado_grado");
					this.Onestado_gradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grado_pensum", Storage="_pensums", ThisKey="ID_grado", OtherKey="id_grado")]
		public EntitySet<pensum> pensums
		{
			get
			{
				return this._pensums;
			}
			set
			{
				this._pensums.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pensums(pensum entity)
		{
			this.SendPropertyChanging();
			entity.grado = this;
		}
		
		private void detach_pensums(pensum entity)
		{
			this.SendPropertyChanging();
			entity.grado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_pensum")]
	public partial class detalle_pensum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Det_Pen;
		
		private string _ID_Curso;
		
		private string _ID_Pensum;
		
		private EntityRef<pensum> _pensum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Det_PenChanging(int value);
    partial void OnID_Det_PenChanged();
    partial void OnID_CursoChanging(string value);
    partial void OnID_CursoChanged();
    partial void OnID_PensumChanging(string value);
    partial void OnID_PensumChanged();
    #endregion
		
		public detalle_pensum()
		{
			this._pensum = default(EntityRef<pensum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Det_Pen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Det_Pen
		{
			get
			{
				return this._ID_Det_Pen;
			}
			set
			{
				if ((this._ID_Det_Pen != value))
				{
					this.OnID_Det_PenChanging(value);
					this.SendPropertyChanging();
					this._ID_Det_Pen = value;
					this.SendPropertyChanged("ID_Det_Pen");
					this.OnID_Det_PenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Curso", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ID_Curso
		{
			get
			{
				return this._ID_Curso;
			}
			set
			{
				if ((this._ID_Curso != value))
				{
					this.OnID_CursoChanging(value);
					this.SendPropertyChanging();
					this._ID_Curso = value;
					this.SendPropertyChanged("ID_Curso");
					this.OnID_CursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pensum", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ID_Pensum
		{
			get
			{
				return this._ID_Pensum;
			}
			set
			{
				if ((this._ID_Pensum != value))
				{
					if (this._pensum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PensumChanging(value);
					this.SendPropertyChanging();
					this._ID_Pensum = value;
					this.SendPropertyChanged("ID_Pensum");
					this.OnID_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pensum_detalle_pensum", Storage="_pensum", ThisKey="ID_Pensum", OtherKey="ID_Pensum", IsForeignKey=true)]
		public pensum pensum
		{
			get
			{
				return this._pensum.Entity;
			}
			set
			{
				pensum previousValue = this._pensum.Entity;
				if (((previousValue != value) 
							|| (this._pensum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pensum.Entity = null;
						previousValue.detalle_pensums.Remove(this);
					}
					this._pensum.Entity = value;
					if ((value != null))
					{
						value.detalle_pensums.Add(this);
						this._ID_Pensum = value.ID_Pensum;
					}
					else
					{
						this._ID_Pensum = default(string);
					}
					this.SendPropertyChanged("pensum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pensum")]
	public partial class pensum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Pensum;
		
		private string _Nom_Pensum;
		
		private int _id_grado;
		
		private System.DateTime _Fecha_Inicio;
		
		private bool _Estado_Pensum;
		
		private string _id_carrera;
		
		private EntitySet<detalle_pensum> _detalle_pensums;
		
		private EntityRef<grado> _grado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PensumChanging(string value);
    partial void OnID_PensumChanged();
    partial void OnNom_PensumChanging(string value);
    partial void OnNom_PensumChanged();
    partial void Onid_gradoChanging(int value);
    partial void Onid_gradoChanged();
    partial void OnFecha_InicioChanging(System.DateTime value);
    partial void OnFecha_InicioChanged();
    partial void OnEstado_PensumChanging(bool value);
    partial void OnEstado_PensumChanged();
    partial void Onid_carreraChanging(string value);
    partial void Onid_carreraChanged();
    #endregion
		
		public pensum()
		{
			this._detalle_pensums = new EntitySet<detalle_pensum>(new Action<detalle_pensum>(this.attach_detalle_pensums), new Action<detalle_pensum>(this.detach_detalle_pensums));
			this._grado = default(EntityRef<grado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pensum", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Pensum
		{
			get
			{
				return this._ID_Pensum;
			}
			set
			{
				if ((this._ID_Pensum != value))
				{
					this.OnID_PensumChanging(value);
					this.SendPropertyChanging();
					this._ID_Pensum = value;
					this.SendPropertyChanged("ID_Pensum");
					this.OnID_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Pensum", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Nom_Pensum
		{
			get
			{
				return this._Nom_Pensum;
			}
			set
			{
				if ((this._Nom_Pensum != value))
				{
					this.OnNom_PensumChanging(value);
					this.SendPropertyChanging();
					this._Nom_Pensum = value;
					this.SendPropertyChanged("Nom_Pensum");
					this.OnNom_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grado", DbType="Int NOT NULL")]
		public int id_grado
		{
			get
			{
				return this._id_grado;
			}
			set
			{
				if ((this._id_grado != value))
				{
					if (this._grado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_gradoChanging(value);
					this.SendPropertyChanging();
					this._id_grado = value;
					this.SendPropertyChanged("id_grado");
					this.Onid_gradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Inicio", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha_Inicio
		{
			get
			{
				return this._Fecha_Inicio;
			}
			set
			{
				if ((this._Fecha_Inicio != value))
				{
					this.OnFecha_InicioChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Inicio = value;
					this.SendPropertyChanged("Fecha_Inicio");
					this.OnFecha_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Pensum", DbType="Bit NOT NULL")]
		public bool Estado_Pensum
		{
			get
			{
				return this._Estado_Pensum;
			}
			set
			{
				if ((this._Estado_Pensum != value))
				{
					this.OnEstado_PensumChanging(value);
					this.SendPropertyChanging();
					this._Estado_Pensum = value;
					this.SendPropertyChanged("Estado_Pensum");
					this.OnEstado_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrera", DbType="NVarChar(5)")]
		public string id_carrera
		{
			get
			{
				return this._id_carrera;
			}
			set
			{
				if ((this._id_carrera != value))
				{
					this.Onid_carreraChanging(value);
					this.SendPropertyChanging();
					this._id_carrera = value;
					this.SendPropertyChanged("id_carrera");
					this.Onid_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pensum_detalle_pensum", Storage="_detalle_pensums", ThisKey="ID_Pensum", OtherKey="ID_Pensum")]
		public EntitySet<detalle_pensum> detalle_pensums
		{
			get
			{
				return this._detalle_pensums;
			}
			set
			{
				this._detalle_pensums.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grado_pensum", Storage="_grado", ThisKey="id_grado", OtherKey="ID_grado", IsForeignKey=true)]
		public grado grado
		{
			get
			{
				return this._grado.Entity;
			}
			set
			{
				grado previousValue = this._grado.Entity;
				if (((previousValue != value) 
							|| (this._grado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grado.Entity = null;
						previousValue.pensums.Remove(this);
					}
					this._grado.Entity = value;
					if ((value != null))
					{
						value.pensums.Add(this);
						this._id_grado = value.ID_grado;
					}
					else
					{
						this._id_grado = default(int);
					}
					this.SendPropertyChanged("grado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_pensums(detalle_pensum entity)
		{
			this.SendPropertyChanging();
			entity.pensum = this;
		}
		
		private void detach_detalle_pensums(detalle_pensum entity)
		{
			this.SendPropertyChanging();
			entity.pensum = null;
		}
	}
}
#pragma warning restore 1591
