#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parcial2_Progra5")]
	public partial class BDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcarrera(carrera instance);
    partial void Updatecarrera(carrera instance);
    partial void Deletecarrera(carrera instance);
    #endregion
		
		public BDDataContext() : 
				base(global::LINQ.Properties.Settings.Default.Parcial2_Progra5ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<carrera> carreras
		{
			get
			{
				return this.GetTable<carrera>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrera")]
	public partial class carrera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_carrera;
		
		private string _nombre_carrera;
		
		private bool _estado_carrera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_carreraChanging(string value);
    partial void Onid_carreraChanged();
    partial void Onnombre_carreraChanging(string value);
    partial void Onnombre_carreraChanged();
    partial void Onestado_carreraChanging(bool value);
    partial void Onestado_carreraChanged();
    #endregion
		
		public carrera()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrera", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_carrera
		{
			get
			{
				return this._id_carrera;
			}
			set
			{
				if ((this._id_carrera != value))
				{
					this.Onid_carreraChanging(value);
					this.SendPropertyChanging();
					this._id_carrera = value;
					this.SendPropertyChanged("id_carrera");
					this.Onid_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_carrera", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_carrera
		{
			get
			{
				return this._nombre_carrera;
			}
			set
			{
				if ((this._nombre_carrera != value))
				{
					this.Onnombre_carreraChanging(value);
					this.SendPropertyChanging();
					this._nombre_carrera = value;
					this.SendPropertyChanged("nombre_carrera");
					this.Onnombre_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_carrera", DbType="Bit NOT NULL")]
		public bool estado_carrera
		{
			get
			{
				return this._estado_carrera;
			}
			set
			{
				if ((this._estado_carrera != value))
				{
					this.Onestado_carreraChanging(value);
					this.SendPropertyChanging();
					this._estado_carrera = value;
					this.SendPropertyChanged("estado_carrera");
					this.Onestado_carreraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
