#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarneAntes.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parcial2_Progra5")]
	public partial class DataClasseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertalumno(alumno instance);
    partial void Updatealumno(alumno instance);
    partial void Deletealumno(alumno instance);
    partial void Insertdetalle_pensum(detalle_pensum instance);
    partial void Updatedetalle_pensum(detalle_pensum instance);
    partial void Deletedetalle_pensum(detalle_pensum instance);
    partial void Insertcarrera(carrera instance);
    partial void Updatecarrera(carrera instance);
    partial void Deletecarrera(carrera instance);
    partial void Insertcurso(curso instance);
    partial void Updatecurso(curso instance);
    partial void Deletecurso(curso instance);
    partial void Insertciclo(ciclo instance);
    partial void Updateciclo(ciclo instance);
    partial void Deleteciclo(ciclo instance);
    partial void Insertpensum(pensum instance);
    partial void Updatepensum(pensum instance);
    partial void Deletepensum(pensum instance);
    partial void Insertinscripcion(inscripcion instance);
    partial void Updateinscripcion(inscripcion instance);
    partial void Deleteinscripcion(inscripcion instance);
    partial void Insertdetalle_pago(detalle_pago instance);
    partial void Updatedetalle_pago(detalle_pago instance);
    partial void Deletedetalle_pago(detalle_pago instance);
    partial void Insertgrado(grado instance);
    partial void Updategrado(grado instance);
    partial void Deletegrado(grado instance);
    partial void Insertjornada(jornada instance);
    partial void Updatejornada(jornada instance);
    partial void Deletejornada(jornada instance);
    partial void Insertnota(nota instance);
    partial void Updatenota(nota instance);
    partial void Deletenota(nota instance);
    partial void Insertseccion(seccion instance);
    partial void Updateseccion(seccion instance);
    partial void Deleteseccion(seccion instance);
    partial void Insertunidad(unidad instance);
    partial void Updateunidad(unidad instance);
    partial void Deleteunidad(unidad instance);
    partial void Insertdepartamento(departamento instance);
    partial void Updatedepartamento(departamento instance);
    partial void Deletedepartamento(departamento instance);
    partial void Insertmunicipio(municipio instance);
    partial void Updatemunicipio(municipio instance);
    partial void Deletemunicipio(municipio instance);
    #endregion
		
		public DataClasseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<alumno> alumnos
		{
			get
			{
				return this.GetTable<alumno>();
			}
		}
		
		public System.Data.Linq.Table<detalle_pensum> detalle_pensum
		{
			get
			{
				return this.GetTable<detalle_pensum>();
			}
		}
		
		public System.Data.Linq.Table<carrera> carrera
		{
			get
			{
				return this.GetTable<carrera>();
			}
		}
		
		public System.Data.Linq.Table<curso> curso
		{
			get
			{
				return this.GetTable<curso>();
			}
		}
		
		public System.Data.Linq.Table<ciclo> ciclo
		{
			get
			{
				return this.GetTable<ciclo>();
			}
		}
		
		public System.Data.Linq.Table<pensum> pensum
		{
			get
			{
				return this.GetTable<pensum>();
			}
		}
		
		public System.Data.Linq.Table<inscripcion> inscripcion
		{
			get
			{
				return this.GetTable<inscripcion>();
			}
		}
		
		public System.Data.Linq.Table<detalle_pago> detalle_pago
		{
			get
			{
				return this.GetTable<detalle_pago>();
			}
		}
		
		public System.Data.Linq.Table<grado> grado
		{
			get
			{
				return this.GetTable<grado>();
			}
		}
		
		public System.Data.Linq.Table<jornada> jornada
		{
			get
			{
				return this.GetTable<jornada>();
			}
		}
		
		public System.Data.Linq.Table<nota> nota
		{
			get
			{
				return this.GetTable<nota>();
			}
		}
		
		public System.Data.Linq.Table<seccion> seccion
		{
			get
			{
				return this.GetTable<seccion>();
			}
		}
		
		public System.Data.Linq.Table<unidad> unidad
		{
			get
			{
				return this.GetTable<unidad>();
			}
		}
		
		public System.Data.Linq.Table<departamento> departamentos
		{
			get
			{
				return this.GetTable<departamento>();
			}
		}
		
		public System.Data.Linq.Table<municipio> municipios
		{
			get
			{
				return this.GetTable<municipio>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumno")]
	public partial class alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Carne;
		
		private string _apellido1_alumno;
		
		private string _apellido2_alumno;
		
		private string _nombre1_alumno;
		
		private string _nombre2_alumno;
		
		private System.Nullable<System.DateTime> _Fechanac;
		
		private string _Sexo_Alumno;
		
		private System.Nullable<int> _estado_alumno;
		
		private string _direccion_alumno;
		
		private string _celular_alumno;
		
		private System.Nullable<System.DateTime> _fechaingreso;
		
		private System.Nullable<int> _id_muni;
		
		private System.Nullable<int> _numero_actualizacion;
		
		private System.Nullable<int> _id_encargado;
		
		private EntitySet<inscripcion> _inscripcion;
		
		private EntityRef<municipio> _municipio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarneChanging(string value);
    partial void OnCarneChanged();
    partial void Onapellido1_alumnoChanging(string value);
    partial void Onapellido1_alumnoChanged();
    partial void Onapellido2_alumnoChanging(string value);
    partial void Onapellido2_alumnoChanged();
    partial void Onnombre1_alumnoChanging(string value);
    partial void Onnombre1_alumnoChanged();
    partial void Onnombre2_alumnoChanging(string value);
    partial void Onnombre2_alumnoChanged();
    partial void OnFechanacChanging(System.Nullable<System.DateTime> value);
    partial void OnFechanacChanged();
    partial void OnSexo_AlumnoChanging(string value);
    partial void OnSexo_AlumnoChanged();
    partial void Onestado_alumnoChanging(System.Nullable<int> value);
    partial void Onestado_alumnoChanged();
    partial void Ondireccion_alumnoChanging(string value);
    partial void Ondireccion_alumnoChanged();
    partial void Oncelular_alumnoChanging(string value);
    partial void Oncelular_alumnoChanged();
    partial void OnfechaingresoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaingresoChanged();
    partial void Onid_muniChanging(System.Nullable<int> value);
    partial void Onid_muniChanged();
    partial void Onnumero_actualizacionChanging(System.Nullable<int> value);
    partial void Onnumero_actualizacionChanged();
    partial void Onid_encargadoChanging(System.Nullable<int> value);
    partial void Onid_encargadoChanged();
    #endregion
		
		public alumno()
		{
			this._inscripcion = new EntitySet<inscripcion>(new Action<inscripcion>(this.attach_inscripcion), new Action<inscripcion>(this.detach_inscripcion));
			this._municipio = default(EntityRef<municipio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carne", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Carne
		{
			get
			{
				return this._Carne;
			}
			set
			{
				if ((this._Carne != value))
				{
					this.OnCarneChanging(value);
					this.SendPropertyChanging();
					this._Carne = value;
					this.SendPropertyChanged("Carne");
					this.OnCarneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido1_alumno", DbType="NVarChar(20)")]
		public string apellido1_alumno
		{
			get
			{
				return this._apellido1_alumno;
			}
			set
			{
				if ((this._apellido1_alumno != value))
				{
					this.Onapellido1_alumnoChanging(value);
					this.SendPropertyChanging();
					this._apellido1_alumno = value;
					this.SendPropertyChanged("apellido1_alumno");
					this.Onapellido1_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido2_alumno", DbType="NVarChar(20)")]
		public string apellido2_alumno
		{
			get
			{
				return this._apellido2_alumno;
			}
			set
			{
				if ((this._apellido2_alumno != value))
				{
					this.Onapellido2_alumnoChanging(value);
					this.SendPropertyChanging();
					this._apellido2_alumno = value;
					this.SendPropertyChanged("apellido2_alumno");
					this.Onapellido2_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre1_alumno", DbType="NVarChar(20)")]
		public string nombre1_alumno
		{
			get
			{
				return this._nombre1_alumno;
			}
			set
			{
				if ((this._nombre1_alumno != value))
				{
					this.Onnombre1_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nombre1_alumno = value;
					this.SendPropertyChanged("nombre1_alumno");
					this.Onnombre1_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre2_alumno", DbType="NVarChar(20)")]
		public string nombre2_alumno
		{
			get
			{
				return this._nombre2_alumno;
			}
			set
			{
				if ((this._nombre2_alumno != value))
				{
					this.Onnombre2_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nombre2_alumno = value;
					this.SendPropertyChanged("nombre2_alumno");
					this.Onnombre2_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fechanac", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fechanac
		{
			get
			{
				return this._Fechanac;
			}
			set
			{
				if ((this._Fechanac != value))
				{
					this.OnFechanacChanging(value);
					this.SendPropertyChanging();
					this._Fechanac = value;
					this.SendPropertyChanged("Fechanac");
					this.OnFechanacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo_Alumno", DbType="NVarChar(20)")]
		public string Sexo_Alumno
		{
			get
			{
				return this._Sexo_Alumno;
			}
			set
			{
				if ((this._Sexo_Alumno != value))
				{
					this.OnSexo_AlumnoChanging(value);
					this.SendPropertyChanging();
					this._Sexo_Alumno = value;
					this.SendPropertyChanged("Sexo_Alumno");
					this.OnSexo_AlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_alumno", DbType="Int")]
		public System.Nullable<int> estado_alumno
		{
			get
			{
				return this._estado_alumno;
			}
			set
			{
				if ((this._estado_alumno != value))
				{
					this.Onestado_alumnoChanging(value);
					this.SendPropertyChanging();
					this._estado_alumno = value;
					this.SendPropertyChanged("estado_alumno");
					this.Onestado_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_alumno", DbType="NVarChar(100)")]
		public string direccion_alumno
		{
			get
			{
				return this._direccion_alumno;
			}
			set
			{
				if ((this._direccion_alumno != value))
				{
					this.Ondireccion_alumnoChanging(value);
					this.SendPropertyChanging();
					this._direccion_alumno = value;
					this.SendPropertyChanged("direccion_alumno");
					this.Ondireccion_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular_alumno", DbType="NVarChar(20)")]
		public string celular_alumno
		{
			get
			{
				return this._celular_alumno;
			}
			set
			{
				if ((this._celular_alumno != value))
				{
					this.Oncelular_alumnoChanging(value);
					this.SendPropertyChanging();
					this._celular_alumno = value;
					this.SendPropertyChanged("celular_alumno");
					this.Oncelular_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaingreso", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaingreso
		{
			get
			{
				return this._fechaingreso;
			}
			set
			{
				if ((this._fechaingreso != value))
				{
					this.OnfechaingresoChanging(value);
					this.SendPropertyChanging();
					this._fechaingreso = value;
					this.SendPropertyChanged("fechaingreso");
					this.OnfechaingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_muni", DbType="Int")]
		public System.Nullable<int> id_muni
		{
			get
			{
				return this._id_muni;
			}
			set
			{
				if ((this._id_muni != value))
				{
					if (this._municipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_muniChanging(value);
					this.SendPropertyChanging();
					this._id_muni = value;
					this.SendPropertyChanged("id_muni");
					this.Onid_muniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_actualizacion", DbType="Int")]
		public System.Nullable<int> numero_actualizacion
		{
			get
			{
				return this._numero_actualizacion;
			}
			set
			{
				if ((this._numero_actualizacion != value))
				{
					this.Onnumero_actualizacionChanging(value);
					this.SendPropertyChanging();
					this._numero_actualizacion = value;
					this.SendPropertyChanged("numero_actualizacion");
					this.Onnumero_actualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_encargado", DbType="Int")]
		public System.Nullable<int> id_encargado
		{
			get
			{
				return this._id_encargado;
			}
			set
			{
				if ((this._id_encargado != value))
				{
					this.Onid_encargadoChanging(value);
					this.SendPropertyChanging();
					this._id_encargado = value;
					this.SendPropertyChanged("id_encargado");
					this.Onid_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_inscripcion", Storage="_inscripcion", ThisKey="Carne", OtherKey="Carne")]
		public EntitySet<inscripcion> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				this._inscripcion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="municipio_alumno", Storage="_municipio", ThisKey="id_muni", OtherKey="id_municipio", IsForeignKey=true)]
		public municipio municipio
		{
			get
			{
				return this._municipio.Entity;
			}
			set
			{
				municipio previousValue = this._municipio.Entity;
				if (((previousValue != value) 
							|| (this._municipio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._municipio.Entity = null;
						previousValue.alumnos.Remove(this);
					}
					this._municipio.Entity = value;
					if ((value != null))
					{
						value.alumnos.Add(this);
						this._id_muni = value.id_municipio;
					}
					else
					{
						this._id_muni = default(Nullable<int>);
					}
					this.SendPropertyChanged("municipio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.alumno = this;
		}
		
		private void detach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.alumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_pensum")]
	public partial class detalle_pensum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Det_Pen;
		
		private string _ID_Curso;
		
		private string _ID_Pensum;
		
		private EntityRef<curso> _curso;
		
		private EntityRef<pensum> _pensum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Det_PenChanging(int value);
    partial void OnID_Det_PenChanged();
    partial void OnID_CursoChanging(string value);
    partial void OnID_CursoChanged();
    partial void OnID_PensumChanging(string value);
    partial void OnID_PensumChanged();
    #endregion
		
		public detalle_pensum()
		{
			this._curso = default(EntityRef<curso>);
			this._pensum = default(EntityRef<pensum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Det_Pen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Det_Pen
		{
			get
			{
				return this._ID_Det_Pen;
			}
			set
			{
				if ((this._ID_Det_Pen != value))
				{
					this.OnID_Det_PenChanging(value);
					this.SendPropertyChanging();
					this._ID_Det_Pen = value;
					this.SendPropertyChanged("ID_Det_Pen");
					this.OnID_Det_PenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Curso", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ID_Curso
		{
			get
			{
				return this._ID_Curso;
			}
			set
			{
				if ((this._ID_Curso != value))
				{
					if (this._curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CursoChanging(value);
					this.SendPropertyChanging();
					this._ID_Curso = value;
					this.SendPropertyChanged("ID_Curso");
					this.OnID_CursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pensum", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ID_Pensum
		{
			get
			{
				return this._ID_Pensum;
			}
			set
			{
				if ((this._ID_Pensum != value))
				{
					if (this._pensum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PensumChanging(value);
					this.SendPropertyChanging();
					this._ID_Pensum = value;
					this.SendPropertyChanged("ID_Pensum");
					this.OnID_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="curso_detalle_pensum", Storage="_curso", ThisKey="ID_Curso", OtherKey="ID_Curso", IsForeignKey=true)]
		public curso curso
		{
			get
			{
				return this._curso.Entity;
			}
			set
			{
				curso previousValue = this._curso.Entity;
				if (((previousValue != value) 
							|| (this._curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._curso.Entity = null;
						previousValue.detalle_pensum.Remove(this);
					}
					this._curso.Entity = value;
					if ((value != null))
					{
						value.detalle_pensum.Add(this);
						this._ID_Curso = value.ID_Curso;
					}
					else
					{
						this._ID_Curso = default(string);
					}
					this.SendPropertyChanged("curso");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pensum_detalle_pensum", Storage="_pensum", ThisKey="ID_Pensum", OtherKey="ID_Pensum", IsForeignKey=true)]
		public pensum pensum
		{
			get
			{
				return this._pensum.Entity;
			}
			set
			{
				pensum previousValue = this._pensum.Entity;
				if (((previousValue != value) 
							|| (this._pensum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pensum.Entity = null;
						previousValue.detalle_pensum.Remove(this);
					}
					this._pensum.Entity = value;
					if ((value != null))
					{
						value.detalle_pensum.Add(this);
						this._ID_Pensum = value.ID_Pensum;
					}
					else
					{
						this._ID_Pensum = default(string);
					}
					this.SendPropertyChanged("pensum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrera")]
	public partial class carrera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_carrera;
		
		private string _nombre_carrera;
		
		private bool _estado_carrera;
		
		private EntitySet<pensum> _pensum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_carreraChanging(string value);
    partial void Onid_carreraChanged();
    partial void Onnombre_carreraChanging(string value);
    partial void Onnombre_carreraChanged();
    partial void Onestado_carreraChanging(bool value);
    partial void Onestado_carreraChanged();
    #endregion
		
		public carrera()
		{
			this._pensum = new EntitySet<pensum>(new Action<pensum>(this.attach_pensum), new Action<pensum>(this.detach_pensum));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrera", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_carrera
		{
			get
			{
				return this._id_carrera;
			}
			set
			{
				if ((this._id_carrera != value))
				{
					this.Onid_carreraChanging(value);
					this.SendPropertyChanging();
					this._id_carrera = value;
					this.SendPropertyChanged("id_carrera");
					this.Onid_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_carrera", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_carrera
		{
			get
			{
				return this._nombre_carrera;
			}
			set
			{
				if ((this._nombre_carrera != value))
				{
					this.Onnombre_carreraChanging(value);
					this.SendPropertyChanging();
					this._nombre_carrera = value;
					this.SendPropertyChanged("nombre_carrera");
					this.Onnombre_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_carrera", DbType="Bit NOT NULL")]
		public bool estado_carrera
		{
			get
			{
				return this._estado_carrera;
			}
			set
			{
				if ((this._estado_carrera != value))
				{
					this.Onestado_carreraChanging(value);
					this.SendPropertyChanging();
					this._estado_carrera = value;
					this.SendPropertyChanged("estado_carrera");
					this.Onestado_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrera_pensum", Storage="_pensum", ThisKey="id_carrera", OtherKey="id_carrera")]
		public EntitySet<pensum> pensum
		{
			get
			{
				return this._pensum;
			}
			set
			{
				this._pensum.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pensum(pensum entity)
		{
			this.SendPropertyChanging();
			entity.carrera = this;
		}
		
		private void detach_pensum(pensum entity)
		{
			this.SendPropertyChanging();
			entity.carrera = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.curso")]
	public partial class curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Curso;
		
		private string _Nom_Curso;
		
		private bool _estado_curso;
		
		private EntitySet<detalle_pensum> _detalle_pensum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CursoChanging(string value);
    partial void OnID_CursoChanged();
    partial void OnNom_CursoChanging(string value);
    partial void OnNom_CursoChanged();
    partial void Onestado_cursoChanging(bool value);
    partial void Onestado_cursoChanged();
    #endregion
		
		public curso()
		{
			this._detalle_pensum = new EntitySet<detalle_pensum>(new Action<detalle_pensum>(this.attach_detalle_pensum), new Action<detalle_pensum>(this.detach_detalle_pensum));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Curso", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Curso
		{
			get
			{
				return this._ID_Curso;
			}
			set
			{
				if ((this._ID_Curso != value))
				{
					this.OnID_CursoChanging(value);
					this.SendPropertyChanging();
					this._ID_Curso = value;
					this.SendPropertyChanged("ID_Curso");
					this.OnID_CursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Curso", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nom_Curso
		{
			get
			{
				return this._Nom_Curso;
			}
			set
			{
				if ((this._Nom_Curso != value))
				{
					this.OnNom_CursoChanging(value);
					this.SendPropertyChanging();
					this._Nom_Curso = value;
					this.SendPropertyChanged("Nom_Curso");
					this.OnNom_CursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_curso", DbType="Bit NOT NULL")]
		public bool estado_curso
		{
			get
			{
				return this._estado_curso;
			}
			set
			{
				if ((this._estado_curso != value))
				{
					this.Onestado_cursoChanging(value);
					this.SendPropertyChanging();
					this._estado_curso = value;
					this.SendPropertyChanged("estado_curso");
					this.Onestado_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="curso_detalle_pensum", Storage="_detalle_pensum", ThisKey="ID_Curso", OtherKey="ID_Curso")]
		public EntitySet<detalle_pensum> detalle_pensum
		{
			get
			{
				return this._detalle_pensum;
			}
			set
			{
				this._detalle_pensum.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_pensum(detalle_pensum entity)
		{
			this.SendPropertyChanging();
			entity.curso = this;
		}
		
		private void detach_detalle_pensum(detalle_pensum entity)
		{
			this.SendPropertyChanging();
			entity.curso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ciclo")]
	public partial class ciclo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ciclo;
		
		private string _nombre_ciclo;
		
		private System.Nullable<bool> _estado_ciclo;
		
		private EntitySet<inscripcion> _inscripcion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cicloChanging(int value);
    partial void Onid_cicloChanged();
    partial void Onnombre_cicloChanging(string value);
    partial void Onnombre_cicloChanged();
    partial void Onestado_cicloChanging(System.Nullable<bool> value);
    partial void Onestado_cicloChanged();
    #endregion
		
		public ciclo()
		{
			this._inscripcion = new EntitySet<inscripcion>(new Action<inscripcion>(this.attach_inscripcion), new Action<inscripcion>(this.detach_inscripcion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ciclo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_ciclo
		{
			get
			{
				return this._id_ciclo;
			}
			set
			{
				if ((this._id_ciclo != value))
				{
					this.Onid_cicloChanging(value);
					this.SendPropertyChanging();
					this._id_ciclo = value;
					this.SendPropertyChanged("id_ciclo");
					this.Onid_cicloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_ciclo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_ciclo
		{
			get
			{
				return this._nombre_ciclo;
			}
			set
			{
				if ((this._nombre_ciclo != value))
				{
					this.Onnombre_cicloChanging(value);
					this.SendPropertyChanging();
					this._nombre_ciclo = value;
					this.SendPropertyChanged("nombre_ciclo");
					this.Onnombre_cicloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_ciclo", DbType="Bit")]
		public System.Nullable<bool> estado_ciclo
		{
			get
			{
				return this._estado_ciclo;
			}
			set
			{
				if ((this._estado_ciclo != value))
				{
					this.Onestado_cicloChanging(value);
					this.SendPropertyChanging();
					this._estado_ciclo = value;
					this.SendPropertyChanged("estado_ciclo");
					this.Onestado_cicloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ciclo_inscripcion", Storage="_inscripcion", ThisKey="id_ciclo", OtherKey="id_ciclo")]
		public EntitySet<inscripcion> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				this._inscripcion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.ciclo = this;
		}
		
		private void detach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.ciclo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pensum")]
	public partial class pensum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Pensum;
		
		private string _Nom_Pensum;
		
		private int _id_grado;
		
		private System.DateTime _Fecha_Inicio;
		
		private bool _Estado_Pensum;
		
		private string _id_carrera;
		
		private EntitySet<detalle_pensum> _detalle_pensum;
		
		private EntitySet<inscripcion> _inscripcion;
		
		private EntityRef<carrera> _carrera;
		
		private EntityRef<grado> _grado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PensumChanging(string value);
    partial void OnID_PensumChanged();
    partial void OnNom_PensumChanging(string value);
    partial void OnNom_PensumChanged();
    partial void Onid_gradoChanging(int value);
    partial void Onid_gradoChanged();
    partial void OnFecha_InicioChanging(System.DateTime value);
    partial void OnFecha_InicioChanged();
    partial void OnEstado_PensumChanging(bool value);
    partial void OnEstado_PensumChanged();
    partial void Onid_carreraChanging(string value);
    partial void Onid_carreraChanged();
    #endregion
		
		public pensum()
		{
			this._detalle_pensum = new EntitySet<detalle_pensum>(new Action<detalle_pensum>(this.attach_detalle_pensum), new Action<detalle_pensum>(this.detach_detalle_pensum));
			this._inscripcion = new EntitySet<inscripcion>(new Action<inscripcion>(this.attach_inscripcion), new Action<inscripcion>(this.detach_inscripcion));
			this._carrera = default(EntityRef<carrera>);
			this._grado = default(EntityRef<grado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pensum", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Pensum
		{
			get
			{
				return this._ID_Pensum;
			}
			set
			{
				if ((this._ID_Pensum != value))
				{
					this.OnID_PensumChanging(value);
					this.SendPropertyChanging();
					this._ID_Pensum = value;
					this.SendPropertyChanged("ID_Pensum");
					this.OnID_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Pensum", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Nom_Pensum
		{
			get
			{
				return this._Nom_Pensum;
			}
			set
			{
				if ((this._Nom_Pensum != value))
				{
					this.OnNom_PensumChanging(value);
					this.SendPropertyChanging();
					this._Nom_Pensum = value;
					this.SendPropertyChanged("Nom_Pensum");
					this.OnNom_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grado", DbType="Int NOT NULL")]
		public int id_grado
		{
			get
			{
				return this._id_grado;
			}
			set
			{
				if ((this._id_grado != value))
				{
					if (this._grado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_gradoChanging(value);
					this.SendPropertyChanging();
					this._id_grado = value;
					this.SendPropertyChanged("id_grado");
					this.Onid_gradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Inicio", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha_Inicio
		{
			get
			{
				return this._Fecha_Inicio;
			}
			set
			{
				if ((this._Fecha_Inicio != value))
				{
					this.OnFecha_InicioChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Inicio = value;
					this.SendPropertyChanged("Fecha_Inicio");
					this.OnFecha_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Pensum", DbType="Bit NOT NULL")]
		public bool Estado_Pensum
		{
			get
			{
				return this._Estado_Pensum;
			}
			set
			{
				if ((this._Estado_Pensum != value))
				{
					this.OnEstado_PensumChanging(value);
					this.SendPropertyChanging();
					this._Estado_Pensum = value;
					this.SendPropertyChanged("Estado_Pensum");
					this.OnEstado_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrera", DbType="NVarChar(5)")]
		public string id_carrera
		{
			get
			{
				return this._id_carrera;
			}
			set
			{
				if ((this._id_carrera != value))
				{
					if (this._carrera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_carreraChanging(value);
					this.SendPropertyChanging();
					this._id_carrera = value;
					this.SendPropertyChanged("id_carrera");
					this.Onid_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pensum_detalle_pensum", Storage="_detalle_pensum", ThisKey="ID_Pensum", OtherKey="ID_Pensum")]
		public EntitySet<detalle_pensum> detalle_pensum
		{
			get
			{
				return this._detalle_pensum;
			}
			set
			{
				this._detalle_pensum.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pensum_inscripcion", Storage="_inscripcion", ThisKey="ID_Pensum", OtherKey="ID_Pensum")]
		public EntitySet<inscripcion> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				this._inscripcion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrera_pensum", Storage="_carrera", ThisKey="id_carrera", OtherKey="id_carrera", IsForeignKey=true)]
		public carrera carrera
		{
			get
			{
				return this._carrera.Entity;
			}
			set
			{
				carrera previousValue = this._carrera.Entity;
				if (((previousValue != value) 
							|| (this._carrera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrera.Entity = null;
						previousValue.pensum.Remove(this);
					}
					this._carrera.Entity = value;
					if ((value != null))
					{
						value.pensum.Add(this);
						this._id_carrera = value.id_carrera;
					}
					else
					{
						this._id_carrera = default(string);
					}
					this.SendPropertyChanged("carrera");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grado_pensum", Storage="_grado", ThisKey="id_grado", OtherKey="ID_grado", IsForeignKey=true)]
		public grado grado
		{
			get
			{
				return this._grado.Entity;
			}
			set
			{
				grado previousValue = this._grado.Entity;
				if (((previousValue != value) 
							|| (this._grado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grado.Entity = null;
						previousValue.pensum.Remove(this);
					}
					this._grado.Entity = value;
					if ((value != null))
					{
						value.pensum.Add(this);
						this._id_grado = value.ID_grado;
					}
					else
					{
						this._id_grado = default(int);
					}
					this.SendPropertyChanged("grado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_pensum(detalle_pensum entity)
		{
			this.SendPropertyChanging();
			entity.pensum = this;
		}
		
		private void detach_detalle_pensum(detalle_pensum entity)
		{
			this.SendPropertyChanging();
			entity.pensum = null;
		}
		
		private void attach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.pensum = this;
		}
		
		private void detach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.pensum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.inscripcion")]
	public partial class inscripcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Inscripcion;
		
		private string _Carne;
		
		private System.DateTime _Fecha_inicial;
		
		private System.DateTime _Fecha_Final;
		
		private bool _Estado_Ins;
		
		private string _ID_Pensum;
		
		private int _id_jornada;
		
		private int _id_ciclo;
		
		private System.Nullable<decimal> _Cantidad_ins;
		
		private System.Nullable<decimal> _Cantidad_mensual;
		
		private System.Nullable<int> _Id_rubro_ins;
		
		private System.Nullable<int> _Id_rubro_men;
		
		private System.Nullable<int> _Contador_mes;
		
		private System.Nullable<decimal> _Total_pagar;
		
		private System.Nullable<System.DateTime> _Fecha_Inscripcion;
		
		private System.Nullable<int> _id_seccion;
		
		private System.Nullable<int> _id_usuario;
		
		private EntityRef<alumno> _alumno;
		
		private EntityRef<ciclo> _ciclo;
		
		private EntityRef<pensum> _pensum;
		
		private EntityRef<jornada> _jornada;
		
		private EntityRef<seccion> _seccion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_InscripcionChanging(int value);
    partial void OnID_InscripcionChanged();
    partial void OnCarneChanging(string value);
    partial void OnCarneChanged();
    partial void OnFecha_inicialChanging(System.DateTime value);
    partial void OnFecha_inicialChanged();
    partial void OnFecha_FinalChanging(System.DateTime value);
    partial void OnFecha_FinalChanged();
    partial void OnEstado_InsChanging(bool value);
    partial void OnEstado_InsChanged();
    partial void OnID_PensumChanging(string value);
    partial void OnID_PensumChanged();
    partial void Onid_jornadaChanging(int value);
    partial void Onid_jornadaChanged();
    partial void Onid_cicloChanging(int value);
    partial void Onid_cicloChanged();
    partial void OnCantidad_insChanging(System.Nullable<decimal> value);
    partial void OnCantidad_insChanged();
    partial void OnCantidad_mensualChanging(System.Nullable<decimal> value);
    partial void OnCantidad_mensualChanged();
    partial void OnId_rubro_insChanging(System.Nullable<int> value);
    partial void OnId_rubro_insChanged();
    partial void OnId_rubro_menChanging(System.Nullable<int> value);
    partial void OnId_rubro_menChanged();
    partial void OnContador_mesChanging(System.Nullable<int> value);
    partial void OnContador_mesChanged();
    partial void OnTotal_pagarChanging(System.Nullable<decimal> value);
    partial void OnTotal_pagarChanged();
    partial void OnFecha_InscripcionChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_InscripcionChanged();
    partial void Onid_seccionChanging(System.Nullable<int> value);
    partial void Onid_seccionChanged();
    partial void Onid_usuarioChanging(System.Nullable<int> value);
    partial void Onid_usuarioChanged();
    #endregion
		
		public inscripcion()
		{
			this._alumno = default(EntityRef<alumno>);
			this._ciclo = default(EntityRef<ciclo>);
			this._pensum = default(EntityRef<pensum>);
			this._jornada = default(EntityRef<jornada>);
			this._seccion = default(EntityRef<seccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Inscripcion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Inscripcion
		{
			get
			{
				return this._ID_Inscripcion;
			}
			set
			{
				if ((this._ID_Inscripcion != value))
				{
					this.OnID_InscripcionChanging(value);
					this.SendPropertyChanging();
					this._ID_Inscripcion = value;
					this.SendPropertyChanged("ID_Inscripcion");
					this.OnID_InscripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carne", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Carne
		{
			get
			{
				return this._Carne;
			}
			set
			{
				if ((this._Carne != value))
				{
					if (this._alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarneChanging(value);
					this.SendPropertyChanging();
					this._Carne = value;
					this.SendPropertyChanged("Carne");
					this.OnCarneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_inicial", DbType="Date NOT NULL")]
		public System.DateTime Fecha_inicial
		{
			get
			{
				return this._Fecha_inicial;
			}
			set
			{
				if ((this._Fecha_inicial != value))
				{
					this.OnFecha_inicialChanging(value);
					this.SendPropertyChanging();
					this._Fecha_inicial = value;
					this.SendPropertyChanged("Fecha_inicial");
					this.OnFecha_inicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Final", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Final
		{
			get
			{
				return this._Fecha_Final;
			}
			set
			{
				if ((this._Fecha_Final != value))
				{
					this.OnFecha_FinalChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Final = value;
					this.SendPropertyChanged("Fecha_Final");
					this.OnFecha_FinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Ins", DbType="Bit NOT NULL")]
		public bool Estado_Ins
		{
			get
			{
				return this._Estado_Ins;
			}
			set
			{
				if ((this._Estado_Ins != value))
				{
					this.OnEstado_InsChanging(value);
					this.SendPropertyChanging();
					this._Estado_Ins = value;
					this.SendPropertyChanged("Estado_Ins");
					this.OnEstado_InsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pensum", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ID_Pensum
		{
			get
			{
				return this._ID_Pensum;
			}
			set
			{
				if ((this._ID_Pensum != value))
				{
					if (this._pensum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PensumChanging(value);
					this.SendPropertyChanging();
					this._ID_Pensum = value;
					this.SendPropertyChanged("ID_Pensum");
					this.OnID_PensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jornada", DbType="Int NOT NULL")]
		public int id_jornada
		{
			get
			{
				return this._id_jornada;
			}
			set
			{
				if ((this._id_jornada != value))
				{
					if (this._jornada.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_jornadaChanging(value);
					this.SendPropertyChanging();
					this._id_jornada = value;
					this.SendPropertyChanged("id_jornada");
					this.Onid_jornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ciclo", DbType="Int NOT NULL")]
		public int id_ciclo
		{
			get
			{
				return this._id_ciclo;
			}
			set
			{
				if ((this._id_ciclo != value))
				{
					if (this._ciclo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_cicloChanging(value);
					this.SendPropertyChanging();
					this._id_ciclo = value;
					this.SendPropertyChanged("id_ciclo");
					this.Onid_cicloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad_ins", DbType="Money")]
		public System.Nullable<decimal> Cantidad_ins
		{
			get
			{
				return this._Cantidad_ins;
			}
			set
			{
				if ((this._Cantidad_ins != value))
				{
					this.OnCantidad_insChanging(value);
					this.SendPropertyChanging();
					this._Cantidad_ins = value;
					this.SendPropertyChanged("Cantidad_ins");
					this.OnCantidad_insChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad_mensual", DbType="Money")]
		public System.Nullable<decimal> Cantidad_mensual
		{
			get
			{
				return this._Cantidad_mensual;
			}
			set
			{
				if ((this._Cantidad_mensual != value))
				{
					this.OnCantidad_mensualChanging(value);
					this.SendPropertyChanging();
					this._Cantidad_mensual = value;
					this.SendPropertyChanged("Cantidad_mensual");
					this.OnCantidad_mensualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_rubro_ins", DbType="Int")]
		public System.Nullable<int> Id_rubro_ins
		{
			get
			{
				return this._Id_rubro_ins;
			}
			set
			{
				if ((this._Id_rubro_ins != value))
				{
					this.OnId_rubro_insChanging(value);
					this.SendPropertyChanging();
					this._Id_rubro_ins = value;
					this.SendPropertyChanged("Id_rubro_ins");
					this.OnId_rubro_insChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_rubro_men", DbType="Int")]
		public System.Nullable<int> Id_rubro_men
		{
			get
			{
				return this._Id_rubro_men;
			}
			set
			{
				if ((this._Id_rubro_men != value))
				{
					this.OnId_rubro_menChanging(value);
					this.SendPropertyChanging();
					this._Id_rubro_men = value;
					this.SendPropertyChanged("Id_rubro_men");
					this.OnId_rubro_menChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contador_mes", DbType="Int")]
		public System.Nullable<int> Contador_mes
		{
			get
			{
				return this._Contador_mes;
			}
			set
			{
				if ((this._Contador_mes != value))
				{
					this.OnContador_mesChanging(value);
					this.SendPropertyChanging();
					this._Contador_mes = value;
					this.SendPropertyChanged("Contador_mes");
					this.OnContador_mesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_pagar", DbType="Money")]
		public System.Nullable<decimal> Total_pagar
		{
			get
			{
				return this._Total_pagar;
			}
			set
			{
				if ((this._Total_pagar != value))
				{
					this.OnTotal_pagarChanging(value);
					this.SendPropertyChanging();
					this._Total_pagar = value;
					this.SendPropertyChanged("Total_pagar");
					this.OnTotal_pagarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Inscripcion", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Inscripcion
		{
			get
			{
				return this._Fecha_Inscripcion;
			}
			set
			{
				if ((this._Fecha_Inscripcion != value))
				{
					this.OnFecha_InscripcionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Inscripcion = value;
					this.SendPropertyChanged("Fecha_Inscripcion");
					this.OnFecha_InscripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_seccion", DbType="Int")]
		public System.Nullable<int> id_seccion
		{
			get
			{
				return this._id_seccion;
			}
			set
			{
				if ((this._id_seccion != value))
				{
					if (this._seccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_seccionChanging(value);
					this.SendPropertyChanging();
					this._id_seccion = value;
					this.SendPropertyChanged("id_seccion");
					this.Onid_seccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int")]
		public System.Nullable<int> id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_inscripcion", Storage="_alumno", ThisKey="Carne", OtherKey="Carne", IsForeignKey=true)]
		public alumno alumno
		{
			get
			{
				return this._alumno.Entity;
			}
			set
			{
				alumno previousValue = this._alumno.Entity;
				if (((previousValue != value) 
							|| (this._alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._alumno.Entity = null;
						previousValue.inscripcion.Remove(this);
					}
					this._alumno.Entity = value;
					if ((value != null))
					{
						value.inscripcion.Add(this);
						this._Carne = value.Carne;
					}
					else
					{
						this._Carne = default(string);
					}
					this.SendPropertyChanged("alumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ciclo_inscripcion", Storage="_ciclo", ThisKey="id_ciclo", OtherKey="id_ciclo", IsForeignKey=true)]
		public ciclo ciclo
		{
			get
			{
				return this._ciclo.Entity;
			}
			set
			{
				ciclo previousValue = this._ciclo.Entity;
				if (((previousValue != value) 
							|| (this._ciclo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ciclo.Entity = null;
						previousValue.inscripcion.Remove(this);
					}
					this._ciclo.Entity = value;
					if ((value != null))
					{
						value.inscripcion.Add(this);
						this._id_ciclo = value.id_ciclo;
					}
					else
					{
						this._id_ciclo = default(int);
					}
					this.SendPropertyChanged("ciclo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pensum_inscripcion", Storage="_pensum", ThisKey="ID_Pensum", OtherKey="ID_Pensum", IsForeignKey=true)]
		public pensum pensum
		{
			get
			{
				return this._pensum.Entity;
			}
			set
			{
				pensum previousValue = this._pensum.Entity;
				if (((previousValue != value) 
							|| (this._pensum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pensum.Entity = null;
						previousValue.inscripcion.Remove(this);
					}
					this._pensum.Entity = value;
					if ((value != null))
					{
						value.inscripcion.Add(this);
						this._ID_Pensum = value.ID_Pensum;
					}
					else
					{
						this._ID_Pensum = default(string);
					}
					this.SendPropertyChanged("pensum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jornada_inscripcion", Storage="_jornada", ThisKey="id_jornada", OtherKey="id_jornada", IsForeignKey=true)]
		public jornada jornada
		{
			get
			{
				return this._jornada.Entity;
			}
			set
			{
				jornada previousValue = this._jornada.Entity;
				if (((previousValue != value) 
							|| (this._jornada.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jornada.Entity = null;
						previousValue.inscripcion.Remove(this);
					}
					this._jornada.Entity = value;
					if ((value != null))
					{
						value.inscripcion.Add(this);
						this._id_jornada = value.id_jornada;
					}
					else
					{
						this._id_jornada = default(int);
					}
					this.SendPropertyChanged("jornada");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="seccion_inscripcion", Storage="_seccion", ThisKey="id_seccion", OtherKey="id_seccion", IsForeignKey=true)]
		public seccion seccion
		{
			get
			{
				return this._seccion.Entity;
			}
			set
			{
				seccion previousValue = this._seccion.Entity;
				if (((previousValue != value) 
							|| (this._seccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._seccion.Entity = null;
						previousValue.inscripcion.Remove(this);
					}
					this._seccion.Entity = value;
					if ((value != null))
					{
						value.inscripcion.Add(this);
						this._id_seccion = value.id_seccion;
					}
					else
					{
						this._id_seccion = default(Nullable<int>);
					}
					this.SendPropertyChanged("seccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_pago")]
	public partial class detalle_pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_det_pago;
		
		private int _id_pago;
		
		private string _id_encpago;
		
		private int _numero_mes;
		
		private System.Nullable<int> _Id_rubro;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<int> _cantidad;
		
		private System.Nullable<decimal> _cantidad_abono;
		
		private System.Nullable<int> _id_inscripcion;
		
		private string _id_curso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_det_pagoChanging(string value);
    partial void Onid_det_pagoChanged();
    partial void Onid_pagoChanging(int value);
    partial void Onid_pagoChanged();
    partial void Onid_encpagoChanging(string value);
    partial void Onid_encpagoChanged();
    partial void Onnumero_mesChanging(int value);
    partial void Onnumero_mesChanged();
    partial void OnId_rubroChanging(System.Nullable<int> value);
    partial void OnId_rubroChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void Oncantidad_abonoChanging(System.Nullable<decimal> value);
    partial void Oncantidad_abonoChanged();
    partial void Onid_inscripcionChanging(System.Nullable<int> value);
    partial void Onid_inscripcionChanged();
    partial void Onid_cursoChanging(string value);
    partial void Onid_cursoChanged();
    #endregion
		
		public detalle_pago()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_det_pago", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_det_pago
		{
			get
			{
				return this._id_det_pago;
			}
			set
			{
				if ((this._id_det_pago != value))
				{
					this.Onid_det_pagoChanging(value);
					this.SendPropertyChanging();
					this._id_det_pago = value;
					this.SendPropertyChanged("id_det_pago");
					this.Onid_det_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pago", DbType="Int NOT NULL")]
		public int id_pago
		{
			get
			{
				return this._id_pago;
			}
			set
			{
				if ((this._id_pago != value))
				{
					this.Onid_pagoChanging(value);
					this.SendPropertyChanging();
					this._id_pago = value;
					this.SendPropertyChanged("id_pago");
					this.Onid_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_encpago", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string id_encpago
		{
			get
			{
				return this._id_encpago;
			}
			set
			{
				if ((this._id_encpago != value))
				{
					this.Onid_encpagoChanging(value);
					this.SendPropertyChanging();
					this._id_encpago = value;
					this.SendPropertyChanged("id_encpago");
					this.Onid_encpagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_mes", DbType="Int NOT NULL")]
		public int numero_mes
		{
			get
			{
				return this._numero_mes;
			}
			set
			{
				if ((this._numero_mes != value))
				{
					this.Onnumero_mesChanging(value);
					this.SendPropertyChanging();
					this._numero_mes = value;
					this.SendPropertyChanged("numero_mes");
					this.Onnumero_mesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_rubro", DbType="Int")]
		public System.Nullable<int> Id_rubro
		{
			get
			{
				return this._Id_rubro;
			}
			set
			{
				if ((this._Id_rubro != value))
				{
					this.OnId_rubroChanging(value);
					this.SendPropertyChanging();
					this._Id_rubro = value;
					this.SendPropertyChanged("Id_rubro");
					this.OnId_rubroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Money")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_abono", DbType="Money")]
		public System.Nullable<decimal> cantidad_abono
		{
			get
			{
				return this._cantidad_abono;
			}
			set
			{
				if ((this._cantidad_abono != value))
				{
					this.Oncantidad_abonoChanging(value);
					this.SendPropertyChanging();
					this._cantidad_abono = value;
					this.SendPropertyChanged("cantidad_abono");
					this.Oncantidad_abonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_inscripcion", DbType="Int")]
		public System.Nullable<int> id_inscripcion
		{
			get
			{
				return this._id_inscripcion;
			}
			set
			{
				if ((this._id_inscripcion != value))
				{
					this.Onid_inscripcionChanging(value);
					this.SendPropertyChanging();
					this._id_inscripcion = value;
					this.SendPropertyChanged("id_inscripcion");
					this.Onid_inscripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_curso", DbType="NVarChar(10)")]
		public string id_curso
		{
			get
			{
				return this._id_curso;
			}
			set
			{
				if ((this._id_curso != value))
				{
					this.Onid_cursoChanging(value);
					this.SendPropertyChanging();
					this._id_curso = value;
					this.SendPropertyChanged("id_curso");
					this.Onid_cursoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grado")]
	public partial class grado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_grado;
		
		private string _Nom_grado;
		
		private bool _estado_grado;
		
		private EntitySet<pensum> _pensum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_gradoChanging(int value);
    partial void OnID_gradoChanged();
    partial void OnNom_gradoChanging(string value);
    partial void OnNom_gradoChanged();
    partial void Onestado_gradoChanging(bool value);
    partial void Onestado_gradoChanged();
    #endregion
		
		public grado()
		{
			this._pensum = new EntitySet<pensum>(new Action<pensum>(this.attach_pensum), new Action<pensum>(this.detach_pensum));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_grado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_grado
		{
			get
			{
				return this._ID_grado;
			}
			set
			{
				if ((this._ID_grado != value))
				{
					this.OnID_gradoChanging(value);
					this.SendPropertyChanging();
					this._ID_grado = value;
					this.SendPropertyChanged("ID_grado");
					this.OnID_gradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_grado", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom_grado
		{
			get
			{
				return this._Nom_grado;
			}
			set
			{
				if ((this._Nom_grado != value))
				{
					this.OnNom_gradoChanging(value);
					this.SendPropertyChanging();
					this._Nom_grado = value;
					this.SendPropertyChanged("Nom_grado");
					this.OnNom_gradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_grado", DbType="Bit NOT NULL")]
		public bool estado_grado
		{
			get
			{
				return this._estado_grado;
			}
			set
			{
				if ((this._estado_grado != value))
				{
					this.Onestado_gradoChanging(value);
					this.SendPropertyChanging();
					this._estado_grado = value;
					this.SendPropertyChanged("estado_grado");
					this.Onestado_gradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grado_pensum", Storage="_pensum", ThisKey="ID_grado", OtherKey="id_grado")]
		public EntitySet<pensum> pensum
		{
			get
			{
				return this._pensum;
			}
			set
			{
				this._pensum.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pensum(pensum entity)
		{
			this.SendPropertyChanging();
			entity.grado = this;
		}
		
		private void detach_pensum(pensum entity)
		{
			this.SendPropertyChanging();
			entity.grado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jornada")]
	public partial class jornada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_jornada;
		
		private string _nombre_jornada;
		
		private EntitySet<inscripcion> _inscripcion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_jornadaChanging(int value);
    partial void Onid_jornadaChanged();
    partial void Onnombre_jornadaChanging(string value);
    partial void Onnombre_jornadaChanged();
    #endregion
		
		public jornada()
		{
			this._inscripcion = new EntitySet<inscripcion>(new Action<inscripcion>(this.attach_inscripcion), new Action<inscripcion>(this.detach_inscripcion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jornada", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_jornada
		{
			get
			{
				return this._id_jornada;
			}
			set
			{
				if ((this._id_jornada != value))
				{
					this.Onid_jornadaChanging(value);
					this.SendPropertyChanging();
					this._id_jornada = value;
					this.SendPropertyChanged("id_jornada");
					this.Onid_jornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_jornada", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_jornada
		{
			get
			{
				return this._nombre_jornada;
			}
			set
			{
				if ((this._nombre_jornada != value))
				{
					this.Onnombre_jornadaChanging(value);
					this.SendPropertyChanging();
					this._nombre_jornada = value;
					this.SendPropertyChanged("nombre_jornada");
					this.Onnombre_jornadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jornada_inscripcion", Storage="_inscripcion", ThisKey="id_jornada", OtherKey="id_jornada")]
		public EntitySet<inscripcion> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				this._inscripcion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.jornada = this;
		}
		
		private void detach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.jornada = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nota")]
	public partial class nota : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Nota;
		
		private System.Nullable<int> _notafinal;
		
		private System.Nullable<int> _id_unidad;
		
		private System.Nullable<int> _ID_CursoProf;
		
		private System.Nullable<int> _zona;
		
		private string _argumento;
		
		private System.Nullable<int> _total;
		
		private string _id_alum_curso;
		
		private string _literal;
		
		private System.Nullable<int> _id_usuario;
		
		private System.Nullable<System.DateTime> _fecha_ingreso;
		
		private string _tipo_nota;
		
		private EntityRef<unidad> _unidad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NotaChanging(string value);
    partial void OnID_NotaChanged();
    partial void OnnotafinalChanging(System.Nullable<int> value);
    partial void OnnotafinalChanged();
    partial void Onid_unidadChanging(System.Nullable<int> value);
    partial void Onid_unidadChanged();
    partial void OnID_CursoProfChanging(System.Nullable<int> value);
    partial void OnID_CursoProfChanged();
    partial void OnzonaChanging(System.Nullable<int> value);
    partial void OnzonaChanged();
    partial void OnargumentoChanging(string value);
    partial void OnargumentoChanged();
    partial void OntotalChanging(System.Nullable<int> value);
    partial void OntotalChanged();
    partial void Onid_alum_cursoChanging(string value);
    partial void Onid_alum_cursoChanged();
    partial void OnliteralChanging(string value);
    partial void OnliteralChanged();
    partial void Onid_usuarioChanging(System.Nullable<int> value);
    partial void Onid_usuarioChanged();
    partial void Onfecha_ingresoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_ingresoChanged();
    partial void Ontipo_notaChanging(string value);
    partial void Ontipo_notaChanged();
    #endregion
		
		public nota()
		{
			this._unidad = default(EntityRef<unidad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Nota", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Nota
		{
			get
			{
				return this._ID_Nota;
			}
			set
			{
				if ((this._ID_Nota != value))
				{
					this.OnID_NotaChanging(value);
					this.SendPropertyChanging();
					this._ID_Nota = value;
					this.SendPropertyChanged("ID_Nota");
					this.OnID_NotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notafinal", DbType="Int")]
		public System.Nullable<int> notafinal
		{
			get
			{
				return this._notafinal;
			}
			set
			{
				if ((this._notafinal != value))
				{
					this.OnnotafinalChanging(value);
					this.SendPropertyChanging();
					this._notafinal = value;
					this.SendPropertyChanged("notafinal");
					this.OnnotafinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_unidad", DbType="Int")]
		public System.Nullable<int> id_unidad
		{
			get
			{
				return this._id_unidad;
			}
			set
			{
				if ((this._id_unidad != value))
				{
					if (this._unidad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_unidadChanging(value);
					this.SendPropertyChanging();
					this._id_unidad = value;
					this.SendPropertyChanged("id_unidad");
					this.Onid_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CursoProf", DbType="Int")]
		public System.Nullable<int> ID_CursoProf
		{
			get
			{
				return this._ID_CursoProf;
			}
			set
			{
				if ((this._ID_CursoProf != value))
				{
					this.OnID_CursoProfChanging(value);
					this.SendPropertyChanging();
					this._ID_CursoProf = value;
					this.SendPropertyChanged("ID_CursoProf");
					this.OnID_CursoProfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zona", DbType="Int")]
		public System.Nullable<int> zona
		{
			get
			{
				return this._zona;
			}
			set
			{
				if ((this._zona != value))
				{
					this.OnzonaChanging(value);
					this.SendPropertyChanging();
					this._zona = value;
					this.SendPropertyChanged("zona");
					this.OnzonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_argumento", DbType="NVarChar(20)")]
		public string argumento
		{
			get
			{
				return this._argumento;
			}
			set
			{
				if ((this._argumento != value))
				{
					this.OnargumentoChanging(value);
					this.SendPropertyChanging();
					this._argumento = value;
					this.SendPropertyChanged("argumento");
					this.OnargumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_alum_curso", DbType="NVarChar(20)")]
		public string id_alum_curso
		{
			get
			{
				return this._id_alum_curso;
			}
			set
			{
				if ((this._id_alum_curso != value))
				{
					this.Onid_alum_cursoChanging(value);
					this.SendPropertyChanging();
					this._id_alum_curso = value;
					this.SendPropertyChanged("id_alum_curso");
					this.Onid_alum_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_literal", DbType="NVarChar(50)")]
		public string literal
		{
			get
			{
				return this._literal;
			}
			set
			{
				if ((this._literal != value))
				{
					this.OnliteralChanging(value);
					this.SendPropertyChanging();
					this._literal = value;
					this.SendPropertyChanged("literal");
					this.OnliteralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int")]
		public System.Nullable<int> id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ingreso", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> fecha_ingreso
		{
			get
			{
				return this._fecha_ingreso;
			}
			set
			{
				if ((this._fecha_ingreso != value))
				{
					this.Onfecha_ingresoChanging(value);
					this.SendPropertyChanging();
					this._fecha_ingreso = value;
					this.SendPropertyChanged("fecha_ingreso");
					this.Onfecha_ingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_nota", DbType="NVarChar(20)")]
		public string tipo_nota
		{
			get
			{
				return this._tipo_nota;
			}
			set
			{
				if ((this._tipo_nota != value))
				{
					this.Ontipo_notaChanging(value);
					this.SendPropertyChanging();
					this._tipo_nota = value;
					this.SendPropertyChanged("tipo_nota");
					this.Ontipo_notaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="unidad_nota", Storage="_unidad", ThisKey="id_unidad", OtherKey="id_unidad", IsForeignKey=true)]
		public unidad unidad
		{
			get
			{
				return this._unidad.Entity;
			}
			set
			{
				unidad previousValue = this._unidad.Entity;
				if (((previousValue != value) 
							|| (this._unidad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._unidad.Entity = null;
						previousValue.nota.Remove(this);
					}
					this._unidad.Entity = value;
					if ((value != null))
					{
						value.nota.Add(this);
						this._id_unidad = value.id_unidad;
					}
					else
					{
						this._id_unidad = default(Nullable<int>);
					}
					this.SendPropertyChanged("unidad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.seccion")]
	public partial class seccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_seccion;
		
		private string _nombre_seccion;
		
		private EntitySet<inscripcion> _inscripcion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_seccionChanging(int value);
    partial void Onid_seccionChanged();
    partial void Onnombre_seccionChanging(string value);
    partial void Onnombre_seccionChanged();
    #endregion
		
		public seccion()
		{
			this._inscripcion = new EntitySet<inscripcion>(new Action<inscripcion>(this.attach_inscripcion), new Action<inscripcion>(this.detach_inscripcion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_seccion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_seccion
		{
			get
			{
				return this._id_seccion;
			}
			set
			{
				if ((this._id_seccion != value))
				{
					this.Onid_seccionChanging(value);
					this.SendPropertyChanging();
					this._id_seccion = value;
					this.SendPropertyChanged("id_seccion");
					this.Onid_seccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_seccion", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string nombre_seccion
		{
			get
			{
				return this._nombre_seccion;
			}
			set
			{
				if ((this._nombre_seccion != value))
				{
					this.Onnombre_seccionChanging(value);
					this.SendPropertyChanging();
					this._nombre_seccion = value;
					this.SendPropertyChanged("nombre_seccion");
					this.Onnombre_seccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="seccion_inscripcion", Storage="_inscripcion", ThisKey="id_seccion", OtherKey="id_seccion")]
		public EntitySet<inscripcion> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				this._inscripcion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.seccion = this;
		}
		
		private void detach_inscripcion(inscripcion entity)
		{
			this.SendPropertyChanging();
			entity.seccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.unidad")]
	public partial class unidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_unidad;
		
		private string _nombre_unidad;
		
		private System.Nullable<System.DateTime> _fecha_inicial;
		
		private System.Nullable<System.DateTime> _fecha_final;
		
		private System.Nullable<bool> _estado_unidad;
		
		private EntitySet<nota> _nota;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_unidadChanging(int value);
    partial void Onid_unidadChanged();
    partial void Onnombre_unidadChanging(string value);
    partial void Onnombre_unidadChanged();
    partial void Onfecha_inicialChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_inicialChanged();
    partial void Onfecha_finalChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_finalChanged();
    partial void Onestado_unidadChanging(System.Nullable<bool> value);
    partial void Onestado_unidadChanged();
    #endregion
		
		public unidad()
		{
			this._nota = new EntitySet<nota>(new Action<nota>(this.attach_nota), new Action<nota>(this.detach_nota));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_unidad", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_unidad
		{
			get
			{
				return this._id_unidad;
			}
			set
			{
				if ((this._id_unidad != value))
				{
					this.Onid_unidadChanging(value);
					this.SendPropertyChanging();
					this._id_unidad = value;
					this.SendPropertyChanged("id_unidad");
					this.Onid_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_unidad", DbType="NVarChar(50)")]
		public string nombre_unidad
		{
			get
			{
				return this._nombre_unidad;
			}
			set
			{
				if ((this._nombre_unidad != value))
				{
					this.Onnombre_unidadChanging(value);
					this.SendPropertyChanging();
					this._nombre_unidad = value;
					this.SendPropertyChanged("nombre_unidad");
					this.Onnombre_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicial", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> fecha_inicial
		{
			get
			{
				return this._fecha_inicial;
			}
			set
			{
				if ((this._fecha_inicial != value))
				{
					this.Onfecha_inicialChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicial = value;
					this.SendPropertyChanged("fecha_inicial");
					this.Onfecha_inicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_final", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> fecha_final
		{
			get
			{
				return this._fecha_final;
			}
			set
			{
				if ((this._fecha_final != value))
				{
					this.Onfecha_finalChanging(value);
					this.SendPropertyChanging();
					this._fecha_final = value;
					this.SendPropertyChanged("fecha_final");
					this.Onfecha_finalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_unidad", DbType="Bit")]
		public System.Nullable<bool> estado_unidad
		{
			get
			{
				return this._estado_unidad;
			}
			set
			{
				if ((this._estado_unidad != value))
				{
					this.Onestado_unidadChanging(value);
					this.SendPropertyChanging();
					this._estado_unidad = value;
					this.SendPropertyChanged("estado_unidad");
					this.Onestado_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="unidad_nota", Storage="_nota", ThisKey="id_unidad", OtherKey="id_unidad")]
		public EntitySet<nota> nota
		{
			get
			{
				return this._nota;
			}
			set
			{
				this._nota.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nota(nota entity)
		{
			this.SendPropertyChanging();
			entity.unidad = this;
		}
		
		private void detach_nota(nota entity)
		{
			this.SendPropertyChanging();
			entity.unidad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.departamento")]
	public partial class departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_departamento;
		
		private string _nombre_departamento;
		
		private EntitySet<municipio> _municipios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_departamentoChanging(int value);
    partial void Onid_departamentoChanged();
    partial void Onnombre_departamentoChanging(string value);
    partial void Onnombre_departamentoChanged();
    #endregion
		
		public departamento()
		{
			this._municipios = new EntitySet<municipio>(new Action<municipio>(this.attach_municipios), new Action<municipio>(this.detach_municipios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_departamento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_departamento
		{
			get
			{
				return this._id_departamento;
			}
			set
			{
				if ((this._id_departamento != value))
				{
					this.Onid_departamentoChanging(value);
					this.SendPropertyChanging();
					this._id_departamento = value;
					this.SendPropertyChanged("id_departamento");
					this.Onid_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_departamento", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_departamento
		{
			get
			{
				return this._nombre_departamento;
			}
			set
			{
				if ((this._nombre_departamento != value))
				{
					this.Onnombre_departamentoChanging(value);
					this.SendPropertyChanging();
					this._nombre_departamento = value;
					this.SendPropertyChanged("nombre_departamento");
					this.Onnombre_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="departamento_municipio", Storage="_municipios", ThisKey="id_departamento", OtherKey="id_departamento")]
		public EntitySet<municipio> municipios
		{
			get
			{
				return this._municipios;
			}
			set
			{
				this._municipios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_municipios(municipio entity)
		{
			this.SendPropertyChanging();
			entity.departamento = this;
		}
		
		private void detach_municipios(municipio entity)
		{
			this.SendPropertyChanging();
			entity.departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.municipio")]
	public partial class municipio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_municipio;
		
		private string _nombre_municipio;
		
		private System.Nullable<int> _id_departamento;
		
		private EntitySet<alumno> _alumnos;
		
		private EntityRef<departamento> _departamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_municipioChanging(int value);
    partial void Onid_municipioChanged();
    partial void Onnombre_municipioChanging(string value);
    partial void Onnombre_municipioChanged();
    partial void Onid_departamentoChanging(System.Nullable<int> value);
    partial void Onid_departamentoChanged();
    #endregion
		
		public municipio()
		{
			this._alumnos = new EntitySet<alumno>(new Action<alumno>(this.attach_alumnos), new Action<alumno>(this.detach_alumnos));
			this._departamento = default(EntityRef<departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_municipio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_municipio
		{
			get
			{
				return this._id_municipio;
			}
			set
			{
				if ((this._id_municipio != value))
				{
					this.Onid_municipioChanging(value);
					this.SendPropertyChanging();
					this._id_municipio = value;
					this.SendPropertyChanged("id_municipio");
					this.Onid_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_municipio", DbType="NVarChar(50)")]
		public string nombre_municipio
		{
			get
			{
				return this._nombre_municipio;
			}
			set
			{
				if ((this._nombre_municipio != value))
				{
					this.Onnombre_municipioChanging(value);
					this.SendPropertyChanging();
					this._nombre_municipio = value;
					this.SendPropertyChanged("nombre_municipio");
					this.Onnombre_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_departamento", DbType="Int")]
		public System.Nullable<int> id_departamento
		{
			get
			{
				return this._id_departamento;
			}
			set
			{
				if ((this._id_departamento != value))
				{
					if (this._departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_departamentoChanging(value);
					this.SendPropertyChanging();
					this._id_departamento = value;
					this.SendPropertyChanged("id_departamento");
					this.Onid_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="municipio_alumno", Storage="_alumnos", ThisKey="id_municipio", OtherKey="id_muni")]
		public EntitySet<alumno> alumnos
		{
			get
			{
				return this._alumnos;
			}
			set
			{
				this._alumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="departamento_municipio", Storage="_departamento", ThisKey="id_departamento", OtherKey="id_departamento", IsForeignKey=true)]
		public departamento departamento
		{
			get
			{
				return this._departamento.Entity;
			}
			set
			{
				departamento previousValue = this._departamento.Entity;
				if (((previousValue != value) 
							|| (this._departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._departamento.Entity = null;
						previousValue.municipios.Remove(this);
					}
					this._departamento.Entity = value;
					if ((value != null))
					{
						value.municipios.Add(this);
						this._id_departamento = value.id_departamento;
					}
					else
					{
						this._id_departamento = default(Nullable<int>);
					}
					this.SendPropertyChanged("departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_alumnos(alumno entity)
		{
			this.SendPropertyChanging();
			entity.municipio = this;
		}
		
		private void detach_alumnos(alumno entity)
		{
			this.SendPropertyChanging();
			entity.municipio = null;
		}
	}
}
#pragma warning restore 1591
