<?xml version="1.0" encoding="utf-8"?><Database Name="Ejercicio1P" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GNARO\SQLEXPRESS;Initial Catalog=Ejercicio1P;Persist Security Info=True;User ID=sa" SettingsObjectName="Parcial01.Properties.Settings" SettingsPropertyName="Ejercicio1PConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="nit_cliente" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_cliente" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_cliente" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="direccion_cliente" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="telefono_cliente" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="fechanac_cliente" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="estado_cliente" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="codigo_municipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cliente_Enca_Compra" Member="Enca_Compra" ThisKey="nit_cliente" OtherKey="dpi_cliente" Type="Enca_Compra" />
    </Type>
  </Table>
  <Table Name="dbo.Departamento" Member="Departamento">
    <Type Name="Departamento">
      <Column Name="codigo_departamento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_departamento" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Detalle_Compra" Member="Detalle_Compra">
    <Type Name="Detalle_Compra">
      <Column Name="codigo_detalle_compra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="precio_costo" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="precio_venta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="subtotal" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="codigo_compra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigo_producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Producto_Detalle_Compra" Member="Producto" ThisKey="codigo_producto" OtherKey="codigo_producto" Type="Producto" IsForeignKey="true" />
      <Association Name="Enca_Compra_Detalle_Compra" Member="Enca_Compra" ThisKey="codigo_compra" OtherKey="codigo_compra" Type="Enca_Compra" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Detalle_Venta" Member="Detalle_Venta">
    <Type Name="Detalle_Venta">
      <Column Name="codigo_detalle_venta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="precio_costo" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="precio_venta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="subtotal" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="codigo_producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigo_venta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Enca_Venta_Detalle_Venta" Member="Enca_Venta" ThisKey="codigo_venta" OtherKey="codigo_venta" Type="Enca_Venta" IsForeignKey="true" />
      <Association Name="Producto_Detalle_Venta" Member="Producto" ThisKey="codigo_producto" OtherKey="codigo_producto" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Enca_Venta" Member="Enca_Venta">
    <Type Name="Enca_Venta">
      <Column Name="codigo_venta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha_venta" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="total_venta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="total_productos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nit_proveedor" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Enca_Venta_Detalle_Venta" Member="Detalle_Venta" ThisKey="codigo_venta" OtherKey="codigo_venta" Type="Detalle_Venta" />
    </Type>
  </Table>
  <Table Name="dbo.Marca" Member="Marca">
    <Type Name="Marca">
      <Column Name="codigo_marca" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_marca" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Marca_Producto" Member="Producto" ThisKey="codigo_marca" OtherKey="codigo_marca" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="codigo_producto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_producto" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="precio_costo" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="precio_venta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="existencia_producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigo_marca" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Producto_Detalle_Compra" Member="Detalle_Compra" ThisKey="codigo_producto" OtherKey="codigo_producto" Type="Detalle_Compra" />
      <Association Name="Producto_Detalle_Venta" Member="Detalle_Venta" ThisKey="codigo_producto" OtherKey="codigo_producto" Type="Detalle_Venta" />
      <Association Name="Marca_Producto" Member="Marca" ThisKey="codigo_marca" OtherKey="codigo_marca" Type="Marca" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_ListadodeClientes" Member="v_ListadodeClientes">
    <Type Name="v_ListadodeClientes">
      <Column Name="NIT" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNac" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.v_ListadoProductos" Member="v_ListadoProductos">
    <Type Name="v_ListadoProductos">
      <Column Name="codigo_producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_producto" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="precio_costo" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="existencia_producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_marca" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Enca_Compra" Member="Enca_Compra">
    <Type Name="Enca_Compra">
      <Column Name="codigo_compra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha_compra" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="total_compra" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="total_producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dpi_cliente" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Enca_Compra_Detalle_Compra" Member="Detalle_Compra" ThisKey="codigo_compra" OtherKey="codigo_compra" Type="Detalle_Compra" />
      <Association Name="Cliente_Enca_Compra" Member="Cliente" ThisKey="dpi_cliente" OtherKey="nit_cliente" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
</Database>