#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial01.BD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ejercicio1P")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    partial void InsertDetalle_Compra(Detalle_Compra instance);
    partial void UpdateDetalle_Compra(Detalle_Compra instance);
    partial void DeleteDetalle_Compra(Detalle_Compra instance);
    partial void InsertDetalle_Venta(Detalle_Venta instance);
    partial void UpdateDetalle_Venta(Detalle_Venta instance);
    partial void DeleteDetalle_Venta(Detalle_Venta instance);
    partial void InsertEnca_Venta(Enca_Venta instance);
    partial void UpdateEnca_Venta(Enca_Venta instance);
    partial void DeleteEnca_Venta(Enca_Venta instance);
    partial void InsertMarca(Marca instance);
    partial void UpdateMarca(Marca instance);
    partial void DeleteMarca(Marca instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertEnca_Compra(Enca_Compra instance);
    partial void UpdateEnca_Compra(Enca_Compra instance);
    partial void DeleteEnca_Compra(Enca_Compra instance);
    partial void InsertProveedor(Proveedor instance);
    partial void UpdateProveedor(Proveedor instance);
    partial void DeleteProveedor(Proveedor instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamento
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Compra> Detalle_Compra
		{
			get
			{
				return this.GetTable<Detalle_Compra>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Venta> Detalle_Venta
		{
			get
			{
				return this.GetTable<Detalle_Venta>();
			}
		}
		
		public System.Data.Linq.Table<Enca_Venta> Enca_Venta
		{
			get
			{
				return this.GetTable<Enca_Venta>();
			}
		}
		
		public System.Data.Linq.Table<Marca> Marca
		{
			get
			{
				return this.GetTable<Marca>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<v_ListadodeClientes> v_ListadodeClientes
		{
			get
			{
				return this.GetTable<v_ListadodeClientes>();
			}
		}
		
		public System.Data.Linq.Table<v_ListadoProductos> v_ListadoProductos
		{
			get
			{
				return this.GetTable<v_ListadoProductos>();
			}
		}
		
		public System.Data.Linq.Table<Enca_Compra> Enca_Compra
		{
			get
			{
				return this.GetTable<Enca_Compra>();
			}
		}
		
		public System.Data.Linq.Table<Proveedor> Proveedors
		{
			get
			{
				return this.GetTable<Proveedor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nit_cliente;
		
		private string _nombre_cliente;
		
		private string _apellido_cliente;
		
		private string _direccion_cliente;
		
		private string _telefono_cliente;
		
		private System.DateTime _fechanac_cliente;
		
		private bool _estado_cliente;
		
		private System.Nullable<int> _codigo_municipio;
		
		private EntitySet<Enca_Compra> _Enca_Compra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnit_clienteChanging(string value);
    partial void Onnit_clienteChanged();
    partial void Onnombre_clienteChanging(string value);
    partial void Onnombre_clienteChanged();
    partial void Onapellido_clienteChanging(string value);
    partial void Onapellido_clienteChanged();
    partial void Ondireccion_clienteChanging(string value);
    partial void Ondireccion_clienteChanged();
    partial void Ontelefono_clienteChanging(string value);
    partial void Ontelefono_clienteChanged();
    partial void Onfechanac_clienteChanging(System.DateTime value);
    partial void Onfechanac_clienteChanged();
    partial void Onestado_clienteChanging(bool value);
    partial void Onestado_clienteChanged();
    partial void Oncodigo_municipioChanging(System.Nullable<int> value);
    partial void Oncodigo_municipioChanged();
    #endregion
		
		public Cliente()
		{
			this._Enca_Compra = new EntitySet<Enca_Compra>(new Action<Enca_Compra>(this.attach_Enca_Compra), new Action<Enca_Compra>(this.detach_Enca_Compra));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_cliente", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nit_cliente
		{
			get
			{
				return this._nit_cliente;
			}
			set
			{
				if ((this._nit_cliente != value))
				{
					this.Onnit_clienteChanging(value);
					this.SendPropertyChanging();
					this._nit_cliente = value;
					this.SendPropertyChanged("nit_cliente");
					this.Onnit_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_cliente", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_cliente
		{
			get
			{
				return this._nombre_cliente;
			}
			set
			{
				if ((this._nombre_cliente != value))
				{
					this.Onnombre_clienteChanging(value);
					this.SendPropertyChanging();
					this._nombre_cliente = value;
					this.SendPropertyChanged("nombre_cliente");
					this.Onnombre_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_cliente", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string apellido_cliente
		{
			get
			{
				return this._apellido_cliente;
			}
			set
			{
				if ((this._apellido_cliente != value))
				{
					this.Onapellido_clienteChanging(value);
					this.SendPropertyChanging();
					this._apellido_cliente = value;
					this.SendPropertyChanged("apellido_cliente");
					this.Onapellido_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_cliente", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string direccion_cliente
		{
			get
			{
				return this._direccion_cliente;
			}
			set
			{
				if ((this._direccion_cliente != value))
				{
					this.Ondireccion_clienteChanging(value);
					this.SendPropertyChanging();
					this._direccion_cliente = value;
					this.SendPropertyChanged("direccion_cliente");
					this.Ondireccion_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_cliente", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string telefono_cliente
		{
			get
			{
				return this._telefono_cliente;
			}
			set
			{
				if ((this._telefono_cliente != value))
				{
					this.Ontelefono_clienteChanging(value);
					this.SendPropertyChanging();
					this._telefono_cliente = value;
					this.SendPropertyChanged("telefono_cliente");
					this.Ontelefono_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechanac_cliente", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fechanac_cliente
		{
			get
			{
				return this._fechanac_cliente;
			}
			set
			{
				if ((this._fechanac_cliente != value))
				{
					this.Onfechanac_clienteChanging(value);
					this.SendPropertyChanging();
					this._fechanac_cliente = value;
					this.SendPropertyChanged("fechanac_cliente");
					this.Onfechanac_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_cliente", DbType="Bit NOT NULL")]
		public bool estado_cliente
		{
			get
			{
				return this._estado_cliente;
			}
			set
			{
				if ((this._estado_cliente != value))
				{
					this.Onestado_clienteChanging(value);
					this.SendPropertyChanging();
					this._estado_cliente = value;
					this.SendPropertyChanged("estado_cliente");
					this.Onestado_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_municipio", DbType="Int")]
		public System.Nullable<int> codigo_municipio
		{
			get
			{
				return this._codigo_municipio;
			}
			set
			{
				if ((this._codigo_municipio != value))
				{
					this.Oncodigo_municipioChanging(value);
					this.SendPropertyChanging();
					this._codigo_municipio = value;
					this.SendPropertyChanged("codigo_municipio");
					this.Oncodigo_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Enca_Compra", Storage="_Enca_Compra", ThisKey="nit_cliente", OtherKey="dpi_cliente")]
		public EntitySet<Enca_Compra> Enca_Compra
		{
			get
			{
				return this._Enca_Compra;
			}
			set
			{
				this._Enca_Compra.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Enca_Compra(Enca_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Enca_Compra(Enca_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_departamento;
		
		private string _nombre_departamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_departamentoChanging(int value);
    partial void Oncodigo_departamentoChanged();
    partial void Onnombre_departamentoChanging(string value);
    partial void Onnombre_departamentoChanged();
    #endregion
		
		public Departamento()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_departamento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codigo_departamento
		{
			get
			{
				return this._codigo_departamento;
			}
			set
			{
				if ((this._codigo_departamento != value))
				{
					this.Oncodigo_departamentoChanging(value);
					this.SendPropertyChanging();
					this._codigo_departamento = value;
					this.SendPropertyChanged("codigo_departamento");
					this.Oncodigo_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_departamento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_departamento
		{
			get
			{
				return this._nombre_departamento;
			}
			set
			{
				if ((this._nombre_departamento != value))
				{
					this.Onnombre_departamentoChanging(value);
					this.SendPropertyChanging();
					this._nombre_departamento = value;
					this.SendPropertyChanged("nombre_departamento");
					this.Onnombre_departamentoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Compra")]
	public partial class Detalle_Compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_detalle_compra;
		
		private int _cantidad;
		
		private decimal _precio_costo;
		
		private decimal _precio_venta;
		
		private decimal _subtotal;
		
		private int _codigo_compra;
		
		private int _codigo_producto;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<Enca_Compra> _Enca_Compra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_detalle_compraChanging(int value);
    partial void Oncodigo_detalle_compraChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void Onprecio_costoChanging(decimal value);
    partial void Onprecio_costoChanged();
    partial void Onprecio_ventaChanging(decimal value);
    partial void Onprecio_ventaChanged();
    partial void OnsubtotalChanging(decimal value);
    partial void OnsubtotalChanged();
    partial void Oncodigo_compraChanging(int value);
    partial void Oncodigo_compraChanged();
    partial void Oncodigo_productoChanging(int value);
    partial void Oncodigo_productoChanged();
    #endregion
		
		public Detalle_Compra()
		{
			this._Producto = default(EntityRef<Producto>);
			this._Enca_Compra = default(EntityRef<Enca_Compra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_detalle_compra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_detalle_compra
		{
			get
			{
				return this._codigo_detalle_compra;
			}
			set
			{
				if ((this._codigo_detalle_compra != value))
				{
					this.Oncodigo_detalle_compraChanging(value);
					this.SendPropertyChanging();
					this._codigo_detalle_compra = value;
					this.SendPropertyChanged("codigo_detalle_compra");
					this.Oncodigo_detalle_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_costo", DbType="Money NOT NULL")]
		public decimal precio_costo
		{
			get
			{
				return this._precio_costo;
			}
			set
			{
				if ((this._precio_costo != value))
				{
					this.Onprecio_costoChanging(value);
					this.SendPropertyChanging();
					this._precio_costo = value;
					this.SendPropertyChanged("precio_costo");
					this.Onprecio_costoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Money NOT NULL")]
		public decimal precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Money NOT NULL")]
		public decimal subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_compra", DbType="Int NOT NULL")]
		public int codigo_compra
		{
			get
			{
				return this._codigo_compra;
			}
			set
			{
				if ((this._codigo_compra != value))
				{
					if (this._Enca_Compra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_compraChanging(value);
					this.SendPropertyChanging();
					this._codigo_compra = value;
					this.SendPropertyChanged("codigo_compra");
					this.Oncodigo_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_producto", DbType="Int NOT NULL")]
		public int codigo_producto
		{
			get
			{
				return this._codigo_producto;
			}
			set
			{
				if ((this._codigo_producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_productoChanging(value);
					this.SendPropertyChanging();
					this._codigo_producto = value;
					this.SendPropertyChanged("codigo_producto");
					this.Oncodigo_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Compra", Storage="_Producto", ThisKey="codigo_producto", OtherKey="codigo_producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Detalle_Compra.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Detalle_Compra.Add(this);
						this._codigo_producto = value.codigo_producto;
					}
					else
					{
						this._codigo_producto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enca_Compra_Detalle_Compra", Storage="_Enca_Compra", ThisKey="codigo_compra", OtherKey="codigo_compra", IsForeignKey=true)]
		public Enca_Compra Enca_Compra
		{
			get
			{
				return this._Enca_Compra.Entity;
			}
			set
			{
				Enca_Compra previousValue = this._Enca_Compra.Entity;
				if (((previousValue != value) 
							|| (this._Enca_Compra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Enca_Compra.Entity = null;
						previousValue.Detalle_Compra.Remove(this);
					}
					this._Enca_Compra.Entity = value;
					if ((value != null))
					{
						value.Detalle_Compra.Add(this);
						this._codigo_compra = value.codigo_compra;
					}
					else
					{
						this._codigo_compra = default(int);
					}
					this.SendPropertyChanged("Enca_Compra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Venta")]
	public partial class Detalle_Venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_detalle_venta;
		
		private int _cantidad;
		
		private decimal _precio_costo;
		
		private decimal _precio_venta;
		
		private decimal _subtotal;
		
		private int _codigo_producto;
		
		private int _codigo_venta;
		
		private EntityRef<Enca_Venta> _Enca_Venta;
		
		private EntityRef<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_detalle_ventaChanging(int value);
    partial void Oncodigo_detalle_ventaChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void Onprecio_costoChanging(decimal value);
    partial void Onprecio_costoChanged();
    partial void Onprecio_ventaChanging(decimal value);
    partial void Onprecio_ventaChanged();
    partial void OnsubtotalChanging(decimal value);
    partial void OnsubtotalChanged();
    partial void Oncodigo_productoChanging(int value);
    partial void Oncodigo_productoChanged();
    partial void Oncodigo_ventaChanging(int value);
    partial void Oncodigo_ventaChanged();
    #endregion
		
		public Detalle_Venta()
		{
			this._Enca_Venta = default(EntityRef<Enca_Venta>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_detalle_venta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_detalle_venta
		{
			get
			{
				return this._codigo_detalle_venta;
			}
			set
			{
				if ((this._codigo_detalle_venta != value))
				{
					this.Oncodigo_detalle_ventaChanging(value);
					this.SendPropertyChanging();
					this._codigo_detalle_venta = value;
					this.SendPropertyChanged("codigo_detalle_venta");
					this.Oncodigo_detalle_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_costo", DbType="Money NOT NULL")]
		public decimal precio_costo
		{
			get
			{
				return this._precio_costo;
			}
			set
			{
				if ((this._precio_costo != value))
				{
					this.Onprecio_costoChanging(value);
					this.SendPropertyChanging();
					this._precio_costo = value;
					this.SendPropertyChanged("precio_costo");
					this.Onprecio_costoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Money NOT NULL")]
		public decimal precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Money NOT NULL")]
		public decimal subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_producto", DbType="Int NOT NULL")]
		public int codigo_producto
		{
			get
			{
				return this._codigo_producto;
			}
			set
			{
				if ((this._codigo_producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_productoChanging(value);
					this.SendPropertyChanging();
					this._codigo_producto = value;
					this.SendPropertyChanged("codigo_producto");
					this.Oncodigo_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_venta", DbType="Int NOT NULL")]
		public int codigo_venta
		{
			get
			{
				return this._codigo_venta;
			}
			set
			{
				if ((this._codigo_venta != value))
				{
					if (this._Enca_Venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_ventaChanging(value);
					this.SendPropertyChanging();
					this._codigo_venta = value;
					this.SendPropertyChanged("codigo_venta");
					this.Oncodigo_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enca_Venta_Detalle_Venta", Storage="_Enca_Venta", ThisKey="codigo_venta", OtherKey="codigo_venta", IsForeignKey=true)]
		public Enca_Venta Enca_Venta
		{
			get
			{
				return this._Enca_Venta.Entity;
			}
			set
			{
				Enca_Venta previousValue = this._Enca_Venta.Entity;
				if (((previousValue != value) 
							|| (this._Enca_Venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Enca_Venta.Entity = null;
						previousValue.Detalle_Venta.Remove(this);
					}
					this._Enca_Venta.Entity = value;
					if ((value != null))
					{
						value.Detalle_Venta.Add(this);
						this._codigo_venta = value.codigo_venta;
					}
					else
					{
						this._codigo_venta = default(int);
					}
					this.SendPropertyChanged("Enca_Venta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Venta", Storage="_Producto", ThisKey="codigo_producto", OtherKey="codigo_producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Detalle_Venta.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Detalle_Venta.Add(this);
						this._codigo_producto = value.codigo_producto;
					}
					else
					{
						this._codigo_producto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Enca_Venta")]
	public partial class Enca_Venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_venta;
		
		private System.DateTime _fecha_venta;
		
		private decimal _total_venta;
		
		private int _total_productos;
		
		private string _nit_proveedor;
		
		private EntitySet<Detalle_Venta> _Detalle_Venta;
		
		private EntityRef<Proveedor> _Proveedor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_ventaChanging(int value);
    partial void Oncodigo_ventaChanged();
    partial void Onfecha_ventaChanging(System.DateTime value);
    partial void Onfecha_ventaChanged();
    partial void Ontotal_ventaChanging(decimal value);
    partial void Ontotal_ventaChanged();
    partial void Ontotal_productosChanging(int value);
    partial void Ontotal_productosChanged();
    partial void Onnit_proveedorChanging(string value);
    partial void Onnit_proveedorChanged();
    #endregion
		
		public Enca_Venta()
		{
			this._Detalle_Venta = new EntitySet<Detalle_Venta>(new Action<Detalle_Venta>(this.attach_Detalle_Venta), new Action<Detalle_Venta>(this.detach_Detalle_Venta));
			this._Proveedor = default(EntityRef<Proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_venta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_venta
		{
			get
			{
				return this._codigo_venta;
			}
			set
			{
				if ((this._codigo_venta != value))
				{
					this.Oncodigo_ventaChanging(value);
					this.SendPropertyChanging();
					this._codigo_venta = value;
					this.SendPropertyChanged("codigo_venta");
					this.Oncodigo_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_venta", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fecha_venta
		{
			get
			{
				return this._fecha_venta;
			}
			set
			{
				if ((this._fecha_venta != value))
				{
					this.Onfecha_ventaChanging(value);
					this.SendPropertyChanging();
					this._fecha_venta = value;
					this.SendPropertyChanged("fecha_venta");
					this.Onfecha_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_venta", DbType="Money NOT NULL")]
		public decimal total_venta
		{
			get
			{
				return this._total_venta;
			}
			set
			{
				if ((this._total_venta != value))
				{
					this.Ontotal_ventaChanging(value);
					this.SendPropertyChanging();
					this._total_venta = value;
					this.SendPropertyChanged("total_venta");
					this.Ontotal_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_productos", DbType="Int NOT NULL")]
		public int total_productos
		{
			get
			{
				return this._total_productos;
			}
			set
			{
				if ((this._total_productos != value))
				{
					this.Ontotal_productosChanging(value);
					this.SendPropertyChanging();
					this._total_productos = value;
					this.SendPropertyChanged("total_productos");
					this.Ontotal_productosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_proveedor", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string nit_proveedor
		{
			get
			{
				return this._nit_proveedor;
			}
			set
			{
				if ((this._nit_proveedor != value))
				{
					if (this._Proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnit_proveedorChanging(value);
					this.SendPropertyChanging();
					this._nit_proveedor = value;
					this.SendPropertyChanged("nit_proveedor");
					this.Onnit_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enca_Venta_Detalle_Venta", Storage="_Detalle_Venta", ThisKey="codigo_venta", OtherKey="codigo_venta")]
		public EntitySet<Detalle_Venta> Detalle_Venta
		{
			get
			{
				return this._Detalle_Venta;
			}
			set
			{
				this._Detalle_Venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_Enca_Venta", Storage="_Proveedor", ThisKey="nit_proveedor", OtherKey="nit_proveedor", IsForeignKey=true)]
		public Proveedor Proveedor
		{
			get
			{
				return this._Proveedor.Entity;
			}
			set
			{
				Proveedor previousValue = this._Proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proveedor.Entity = null;
						previousValue.Enca_Ventas.Remove(this);
					}
					this._Proveedor.Entity = value;
					if ((value != null))
					{
						value.Enca_Ventas.Add(this);
						this._nit_proveedor = value.nit_proveedor;
					}
					else
					{
						this._nit_proveedor = default(string);
					}
					this.SendPropertyChanged("Proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Enca_Venta = this;
		}
		
		private void detach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Enca_Venta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marca")]
	public partial class Marca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_marca;
		
		private string _nombre_marca;
		
		private EntitySet<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_marcaChanging(int value);
    partial void Oncodigo_marcaChanged();
    partial void Onnombre_marcaChanging(string value);
    partial void Onnombre_marcaChanged();
    #endregion
		
		public Marca()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_marca", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codigo_marca
		{
			get
			{
				return this._codigo_marca;
			}
			set
			{
				if ((this._codigo_marca != value))
				{
					this.Oncodigo_marcaChanging(value);
					this.SendPropertyChanging();
					this._codigo_marca = value;
					this.SendPropertyChanged("codigo_marca");
					this.Oncodigo_marcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_marca", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_marca
		{
			get
			{
				return this._nombre_marca;
			}
			set
			{
				if ((this._nombre_marca != value))
				{
					this.Onnombre_marcaChanging(value);
					this.SendPropertyChanging();
					this._nombre_marca = value;
					this.SendPropertyChanged("nombre_marca");
					this.Onnombre_marcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Producto", Storage="_Producto", ThisKey="codigo_marca", OtherKey="codigo_marca")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Marca = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Marca = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_producto;
		
		private string _nombre_producto;
		
		private decimal _precio_costo;
		
		private decimal _precio_venta;
		
		private int _existencia_producto;
		
		private int _codigo_marca;
		
		private EntitySet<Detalle_Compra> _Detalle_Compra;
		
		private EntitySet<Detalle_Venta> _Detalle_Venta;
		
		private EntityRef<Marca> _Marca;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_productoChanging(int value);
    partial void Oncodigo_productoChanged();
    partial void Onnombre_productoChanging(string value);
    partial void Onnombre_productoChanged();
    partial void Onprecio_costoChanging(decimal value);
    partial void Onprecio_costoChanged();
    partial void Onprecio_ventaChanging(decimal value);
    partial void Onprecio_ventaChanged();
    partial void Onexistencia_productoChanging(int value);
    partial void Onexistencia_productoChanged();
    partial void Oncodigo_marcaChanging(int value);
    partial void Oncodigo_marcaChanged();
    #endregion
		
		public Producto()
		{
			this._Detalle_Compra = new EntitySet<Detalle_Compra>(new Action<Detalle_Compra>(this.attach_Detalle_Compra), new Action<Detalle_Compra>(this.detach_Detalle_Compra));
			this._Detalle_Venta = new EntitySet<Detalle_Venta>(new Action<Detalle_Venta>(this.attach_Detalle_Venta), new Action<Detalle_Venta>(this.detach_Detalle_Venta));
			this._Marca = default(EntityRef<Marca>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_producto
		{
			get
			{
				return this._codigo_producto;
			}
			set
			{
				if ((this._codigo_producto != value))
				{
					this.Oncodigo_productoChanging(value);
					this.SendPropertyChanging();
					this._codigo_producto = value;
					this.SendPropertyChanged("codigo_producto");
					this.Oncodigo_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_producto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_producto
		{
			get
			{
				return this._nombre_producto;
			}
			set
			{
				if ((this._nombre_producto != value))
				{
					this.Onnombre_productoChanging(value);
					this.SendPropertyChanging();
					this._nombre_producto = value;
					this.SendPropertyChanged("nombre_producto");
					this.Onnombre_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_costo", DbType="Money NOT NULL")]
		public decimal precio_costo
		{
			get
			{
				return this._precio_costo;
			}
			set
			{
				if ((this._precio_costo != value))
				{
					this.Onprecio_costoChanging(value);
					this.SendPropertyChanging();
					this._precio_costo = value;
					this.SendPropertyChanged("precio_costo");
					this.Onprecio_costoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Money NOT NULL")]
		public decimal precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_existencia_producto", DbType="Int NOT NULL")]
		public int existencia_producto
		{
			get
			{
				return this._existencia_producto;
			}
			set
			{
				if ((this._existencia_producto != value))
				{
					this.Onexistencia_productoChanging(value);
					this.SendPropertyChanging();
					this._existencia_producto = value;
					this.SendPropertyChanged("existencia_producto");
					this.Onexistencia_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_marca", DbType="Int NOT NULL")]
		public int codigo_marca
		{
			get
			{
				return this._codigo_marca;
			}
			set
			{
				if ((this._codigo_marca != value))
				{
					if (this._Marca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_marcaChanging(value);
					this.SendPropertyChanging();
					this._codigo_marca = value;
					this.SendPropertyChanged("codigo_marca");
					this.Oncodigo_marcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Compra", Storage="_Detalle_Compra", ThisKey="codigo_producto", OtherKey="codigo_producto")]
		public EntitySet<Detalle_Compra> Detalle_Compra
		{
			get
			{
				return this._Detalle_Compra;
			}
			set
			{
				this._Detalle_Compra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Venta", Storage="_Detalle_Venta", ThisKey="codigo_producto", OtherKey="codigo_producto")]
		public EntitySet<Detalle_Venta> Detalle_Venta
		{
			get
			{
				return this._Detalle_Venta;
			}
			set
			{
				this._Detalle_Venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Producto", Storage="_Marca", ThisKey="codigo_marca", OtherKey="codigo_marca", IsForeignKey=true)]
		public Marca Marca
		{
			get
			{
				return this._Marca.Entity;
			}
			set
			{
				Marca previousValue = this._Marca.Entity;
				if (((previousValue != value) 
							|| (this._Marca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marca.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Marca.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._codigo_marca = value.codigo_marca;
					}
					else
					{
						this._codigo_marca = default(int);
					}
					this.SendPropertyChanged("Marca");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Compra(Detalle_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Detalle_Compra(Detalle_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_ListadodeClientes")]
	public partial class v_ListadodeClientes
	{
		
		private string _NIT;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Direccion;
		
		private System.DateTime _FechaNac;
		
		public v_ListadodeClientes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this._NIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNac", DbType="SmallDateTime NOT NULL")]
		public System.DateTime FechaNac
		{
			get
			{
				return this._FechaNac;
			}
			set
			{
				if ((this._FechaNac != value))
				{
					this._FechaNac = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_ListadoProductos")]
	public partial class v_ListadoProductos
	{
		
		private int _codigo_producto;
		
		private string _nombre_producto;
		
		private decimal _precio_costo;
		
		private int _existencia_producto;
		
		private string _nombre_marca;
		
		public v_ListadoProductos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_producto", DbType="Int NOT NULL")]
		public int codigo_producto
		{
			get
			{
				return this._codigo_producto;
			}
			set
			{
				if ((this._codigo_producto != value))
				{
					this._codigo_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_producto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_producto
		{
			get
			{
				return this._nombre_producto;
			}
			set
			{
				if ((this._nombre_producto != value))
				{
					this._nombre_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_costo", DbType="Money NOT NULL")]
		public decimal precio_costo
		{
			get
			{
				return this._precio_costo;
			}
			set
			{
				if ((this._precio_costo != value))
				{
					this._precio_costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_existencia_producto", DbType="Int NOT NULL")]
		public int existencia_producto
		{
			get
			{
				return this._existencia_producto;
			}
			set
			{
				if ((this._existencia_producto != value))
				{
					this._existencia_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_marca", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_marca
		{
			get
			{
				return this._nombre_marca;
			}
			set
			{
				if ((this._nombre_marca != value))
				{
					this._nombre_marca = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Enca_Compra")]
	public partial class Enca_Compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_compra;
		
		private System.DateTime _fecha_compra;
		
		private decimal _total_compra;
		
		private int _total_producto;
		
		private string _dpi_cliente;
		
		private EntitySet<Detalle_Compra> _Detalle_Compra;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_compraChanging(int value);
    partial void Oncodigo_compraChanged();
    partial void Onfecha_compraChanging(System.DateTime value);
    partial void Onfecha_compraChanged();
    partial void Ontotal_compraChanging(decimal value);
    partial void Ontotal_compraChanged();
    partial void Ontotal_productoChanging(int value);
    partial void Ontotal_productoChanged();
    partial void Ondpi_clienteChanging(string value);
    partial void Ondpi_clienteChanged();
    #endregion
		
		public Enca_Compra()
		{
			this._Detalle_Compra = new EntitySet<Detalle_Compra>(new Action<Detalle_Compra>(this.attach_Detalle_Compra), new Action<Detalle_Compra>(this.detach_Detalle_Compra));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_compra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_compra
		{
			get
			{
				return this._codigo_compra;
			}
			set
			{
				if ((this._codigo_compra != value))
				{
					this.Oncodigo_compraChanging(value);
					this.SendPropertyChanging();
					this._codigo_compra = value;
					this.SendPropertyChanged("codigo_compra");
					this.Oncodigo_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_compra", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fecha_compra
		{
			get
			{
				return this._fecha_compra;
			}
			set
			{
				if ((this._fecha_compra != value))
				{
					this.Onfecha_compraChanging(value);
					this.SendPropertyChanging();
					this._fecha_compra = value;
					this.SendPropertyChanged("fecha_compra");
					this.Onfecha_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_compra", DbType="Money NOT NULL")]
		public decimal total_compra
		{
			get
			{
				return this._total_compra;
			}
			set
			{
				if ((this._total_compra != value))
				{
					this.Ontotal_compraChanging(value);
					this.SendPropertyChanging();
					this._total_compra = value;
					this.SendPropertyChanged("total_compra");
					this.Ontotal_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_producto", DbType="Int NOT NULL")]
		public int total_producto
		{
			get
			{
				return this._total_producto;
			}
			set
			{
				if ((this._total_producto != value))
				{
					this.Ontotal_productoChanging(value);
					this.SendPropertyChanging();
					this._total_producto = value;
					this.SendPropertyChanged("total_producto");
					this.Ontotal_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi_cliente", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string dpi_cliente
		{
			get
			{
				return this._dpi_cliente;
			}
			set
			{
				if ((this._dpi_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondpi_clienteChanging(value);
					this.SendPropertyChanging();
					this._dpi_cliente = value;
					this.SendPropertyChanged("dpi_cliente");
					this.Ondpi_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enca_Compra_Detalle_Compra", Storage="_Detalle_Compra", ThisKey="codigo_compra", OtherKey="codigo_compra")]
		public EntitySet<Detalle_Compra> Detalle_Compra
		{
			get
			{
				return this._Detalle_Compra;
			}
			set
			{
				this._Detalle_Compra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Enca_Compra", Storage="_Cliente", ThisKey="dpi_cliente", OtherKey="nit_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Enca_Compra.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Enca_Compra.Add(this);
						this._dpi_cliente = value.nit_cliente;
					}
					else
					{
						this._dpi_cliente = default(string);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Compra(Detalle_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Enca_Compra = this;
		}
		
		private void detach_Detalle_Compra(Detalle_Compra entity)
		{
			this.SendPropertyChanging();
			entity.Enca_Compra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedor")]
	public partial class Proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nit_proveedor;
		
		private string _nombre_proveedor;
		
		private string _direccion_proveedor;
		
		private string _telefono_proveedor;
		
		private EntitySet<Enca_Venta> _Enca_Ventas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnit_proveedorChanging(string value);
    partial void Onnit_proveedorChanged();
    partial void Onnombre_proveedorChanging(string value);
    partial void Onnombre_proveedorChanged();
    partial void Ondireccion_proveedorChanging(string value);
    partial void Ondireccion_proveedorChanged();
    partial void Ontelefono_proveedorChanging(string value);
    partial void Ontelefono_proveedorChanged();
    #endregion
		
		public Proveedor()
		{
			this._Enca_Ventas = new EntitySet<Enca_Venta>(new Action<Enca_Venta>(this.attach_Enca_Ventas), new Action<Enca_Venta>(this.detach_Enca_Ventas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_proveedor", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nit_proveedor
		{
			get
			{
				return this._nit_proveedor;
			}
			set
			{
				if ((this._nit_proveedor != value))
				{
					this.Onnit_proveedorChanging(value);
					this.SendPropertyChanging();
					this._nit_proveedor = value;
					this.SendPropertyChanged("nit_proveedor");
					this.Onnit_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_proveedor", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string nombre_proveedor
		{
			get
			{
				return this._nombre_proveedor;
			}
			set
			{
				if ((this._nombre_proveedor != value))
				{
					this.Onnombre_proveedorChanging(value);
					this.SendPropertyChanging();
					this._nombre_proveedor = value;
					this.SendPropertyChanged("nombre_proveedor");
					this.Onnombre_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_proveedor", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string direccion_proveedor
		{
			get
			{
				return this._direccion_proveedor;
			}
			set
			{
				if ((this._direccion_proveedor != value))
				{
					this.Ondireccion_proveedorChanging(value);
					this.SendPropertyChanging();
					this._direccion_proveedor = value;
					this.SendPropertyChanged("direccion_proveedor");
					this.Ondireccion_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_proveedor", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string telefono_proveedor
		{
			get
			{
				return this._telefono_proveedor;
			}
			set
			{
				if ((this._telefono_proveedor != value))
				{
					this.Ontelefono_proveedorChanging(value);
					this.SendPropertyChanging();
					this._telefono_proveedor = value;
					this.SendPropertyChanged("telefono_proveedor");
					this.Ontelefono_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_Enca_Venta", Storage="_Enca_Ventas", ThisKey="nit_proveedor", OtherKey="nit_proveedor")]
		public EntitySet<Enca_Venta> Enca_Ventas
		{
			get
			{
				return this._Enca_Ventas;
			}
			set
			{
				this._Enca_Ventas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Enca_Ventas(Enca_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = this;
		}
		
		private void detach_Enca_Ventas(Enca_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = null;
		}
	}
}
#pragma warning restore 1591
