#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial2Web.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parcial2_BD")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    partial void InsertAsignacion(Asignacion instance);
    partial void UpdateAsignacion(Asignacion instance);
    partial void DeleteAsignacion(Asignacion instance);
    partial void InsertCiclo(Ciclo instance);
    partial void UpdateCiclo(Ciclo instance);
    partial void DeleteCiclo(Ciclo instance);
    partial void InsertCurso(Curso instance);
    partial void UpdateCurso(Curso instance);
    partial void DeleteCurso(Curso instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    partial void InsertMunicipio(Municipio instance);
    partial void UpdateMunicipio(Municipio instance);
    partial void DeleteMunicipio(Municipio instance);
    partial void InsertProfesor(Profesor instance);
    partial void UpdateProfesor(Profesor instance);
    partial void DeleteProfesor(Profesor instance);
    partial void InsertProfesor_Curso(Profesor_Curso instance);
    partial void UpdateProfesor_Curso(Profesor_Curso instance);
    partial void DeleteProfesor_Curso(Profesor_Curso instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Alumno> Alumno
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
		
		public System.Data.Linq.Table<Asignacion> Asignacion
		{
			get
			{
				return this.GetTable<Asignacion>();
			}
		}
		
		public System.Data.Linq.Table<Ciclo> Ciclo
		{
			get
			{
				return this.GetTable<Ciclo>();
			}
		}
		
		public System.Data.Linq.Table<Curso> Curso
		{
			get
			{
				return this.GetTable<Curso>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamento
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Municipio> Municipio
		{
			get
			{
				return this.GetTable<Municipio>();
			}
		}
		
		public System.Data.Linq.Table<Profesor> Profesor
		{
			get
			{
				return this.GetTable<Profesor>();
			}
		}
		
		public System.Data.Linq.Table<Profesor_Curso> Profesor_Curso
		{
			get
			{
				return this.GetTable<Profesor_Curso>();
			}
		}
		
		public System.Data.Linq.Table<VistaAlumno> VistaAlumno
		{
			get
			{
				return this.GetTable<VistaAlumno>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codigo_alumno;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.DateTime _fecha_nac;
		
		private string _direccion;
		
		private string _correo;
		
		private string _telefono;
		
		private string _usuario_alumno;
		
		private string _contrasenia;
		
		private string _cod_municipio;
		
		private EntitySet<Asignacion> _Asignacion;
		
		private EntityRef<Municipio> _Municipio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_alumnoChanging(string value);
    partial void Oncodigo_alumnoChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void Onfecha_nacChanging(System.DateTime value);
    partial void Onfecha_nacChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void Onusuario_alumnoChanging(string value);
    partial void Onusuario_alumnoChanged();
    partial void OncontraseniaChanging(string value);
    partial void OncontraseniaChanged();
    partial void Oncod_municipioChanging(string value);
    partial void Oncod_municipioChanged();
    #endregion
		
		public Alumno()
		{
			this._Asignacion = new EntitySet<Asignacion>(new Action<Asignacion>(this.attach_Asignacion), new Action<Asignacion>(this.detach_Asignacion));
			this._Municipio = default(EntityRef<Municipio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_alumno", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codigo_alumno
		{
			get
			{
				return this._codigo_alumno;
			}
			set
			{
				if ((this._codigo_alumno != value))
				{
					this.Oncodigo_alumnoChanging(value);
					this.SendPropertyChanging();
					this._codigo_alumno = value;
					this.SendPropertyChanged("codigo_alumno");
					this.Oncodigo_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nac", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fecha_nac
		{
			get
			{
				return this._fecha_nac;
			}
			set
			{
				if ((this._fecha_nac != value))
				{
					this.Onfecha_nacChanging(value);
					this.SendPropertyChanging();
					this._fecha_nac = value;
					this.SendPropertyChanged("fecha_nac");
					this.Onfecha_nacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_alumno", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string usuario_alumno
		{
			get
			{
				return this._usuario_alumno;
			}
			set
			{
				if ((this._usuario_alumno != value))
				{
					this.Onusuario_alumnoChanging(value);
					this.SendPropertyChanging();
					this._usuario_alumno = value;
					this.SendPropertyChanged("usuario_alumno");
					this.Onusuario_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenia", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string contrasenia
		{
			get
			{
				return this._contrasenia;
			}
			set
			{
				if ((this._contrasenia != value))
				{
					this.OncontraseniaChanging(value);
					this.SendPropertyChanging();
					this._contrasenia = value;
					this.SendPropertyChanged("contrasenia");
					this.OncontraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_municipio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cod_municipio
		{
			get
			{
				return this._cod_municipio;
			}
			set
			{
				if ((this._cod_municipio != value))
				{
					if (this._Municipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_municipioChanging(value);
					this.SendPropertyChanging();
					this._cod_municipio = value;
					this.SendPropertyChanged("cod_municipio");
					this.Oncod_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Asignacion", Storage="_Asignacion", ThisKey="codigo_alumno", OtherKey="codigo_alumno")]
		public EntitySet<Asignacion> Asignacion
		{
			get
			{
				return this._Asignacion;
			}
			set
			{
				this._Asignacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_Alumno", Storage="_Municipio", ThisKey="cod_municipio", OtherKey="cod_municipio", IsForeignKey=true)]
		public Municipio Municipio
		{
			get
			{
				return this._Municipio.Entity;
			}
			set
			{
				Municipio previousValue = this._Municipio.Entity;
				if (((previousValue != value) 
							|| (this._Municipio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Municipio.Entity = null;
						previousValue.Alumno.Remove(this);
					}
					this._Municipio.Entity = value;
					if ((value != null))
					{
						value.Alumno.Add(this);
						this._cod_municipio = value.cod_municipio;
					}
					else
					{
						this._cod_municipio = default(string);
					}
					this.SendPropertyChanged("Municipio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asignacion(Asignacion entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = this;
		}
		
		private void detach_Asignacion(Asignacion entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asignacion")]
	public partial class Asignacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_asignacion;
		
		private System.DateTime _fecha_asignacion;
		
		private int _zona;
		
		private int _final;
		
		private int _total;
		
		private string _resultado;
		
		private bool _estado_delegado;
		
		private string _codigo_alumno;
		
		private int _codigo_prof_curso;
		
		private EntityRef<Alumno> _Alumno;
		
		private EntityRef<Profesor_Curso> _Profesor_Curso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_asignacionChanging(int value);
    partial void Oncodigo_asignacionChanged();
    partial void Onfecha_asignacionChanging(System.DateTime value);
    partial void Onfecha_asignacionChanged();
    partial void OnzonaChanging(int value);
    partial void OnzonaChanged();
    partial void OnfinalChanging(int value);
    partial void OnfinalChanged();
    partial void OntotalChanging(int value);
    partial void OntotalChanged();
    partial void OnresultadoChanging(string value);
    partial void OnresultadoChanged();
    partial void Onestado_delegadoChanging(bool value);
    partial void Onestado_delegadoChanged();
    partial void Oncodigo_alumnoChanging(string value);
    partial void Oncodigo_alumnoChanged();
    partial void Oncodigo_prof_cursoChanging(int value);
    partial void Oncodigo_prof_cursoChanged();
    #endregion
		
		public Asignacion()
		{
			this._Alumno = default(EntityRef<Alumno>);
			this._Profesor_Curso = default(EntityRef<Profesor_Curso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_asignacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_asignacion
		{
			get
			{
				return this._codigo_asignacion;
			}
			set
			{
				if ((this._codigo_asignacion != value))
				{
					this.Oncodigo_asignacionChanging(value);
					this.SendPropertyChanging();
					this._codigo_asignacion = value;
					this.SendPropertyChanged("codigo_asignacion");
					this.Oncodigo_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_asignacion", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fecha_asignacion
		{
			get
			{
				return this._fecha_asignacion;
			}
			set
			{
				if ((this._fecha_asignacion != value))
				{
					this.Onfecha_asignacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_asignacion = value;
					this.SendPropertyChanged("fecha_asignacion");
					this.Onfecha_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zona", DbType="Int NOT NULL")]
		public int zona
		{
			get
			{
				return this._zona;
			}
			set
			{
				if ((this._zona != value))
				{
					this.OnzonaChanging(value);
					this.SendPropertyChanging();
					this._zona = value;
					this.SendPropertyChanged("zona");
					this.OnzonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final", DbType="Int NOT NULL")]
		public int final
		{
			get
			{
				return this._final;
			}
			set
			{
				if ((this._final != value))
				{
					this.OnfinalChanging(value);
					this.SendPropertyChanging();
					this._final = value;
					this.SendPropertyChanged("final");
					this.OnfinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int NOT NULL")]
		public int total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultado", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string resultado
		{
			get
			{
				return this._resultado;
			}
			set
			{
				if ((this._resultado != value))
				{
					this.OnresultadoChanging(value);
					this.SendPropertyChanging();
					this._resultado = value;
					this.SendPropertyChanged("resultado");
					this.OnresultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_delegado", DbType="Bit NOT NULL")]
		public bool estado_delegado
		{
			get
			{
				return this._estado_delegado;
			}
			set
			{
				if ((this._estado_delegado != value))
				{
					this.Onestado_delegadoChanging(value);
					this.SendPropertyChanging();
					this._estado_delegado = value;
					this.SendPropertyChanged("estado_delegado");
					this.Onestado_delegadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_alumno", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string codigo_alumno
		{
			get
			{
				return this._codigo_alumno;
			}
			set
			{
				if ((this._codigo_alumno != value))
				{
					if (this._Alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_alumnoChanging(value);
					this.SendPropertyChanging();
					this._codigo_alumno = value;
					this.SendPropertyChanged("codigo_alumno");
					this.Oncodigo_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_prof_curso", DbType="Int NOT NULL")]
		public int codigo_prof_curso
		{
			get
			{
				return this._codigo_prof_curso;
			}
			set
			{
				if ((this._codigo_prof_curso != value))
				{
					if (this._Profesor_Curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_prof_cursoChanging(value);
					this.SendPropertyChanging();
					this._codigo_prof_curso = value;
					this.SendPropertyChanged("codigo_prof_curso");
					this.Oncodigo_prof_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Asignacion", Storage="_Alumno", ThisKey="codigo_alumno", OtherKey="codigo_alumno", IsForeignKey=true)]
		public Alumno Alumno
		{
			get
			{
				return this._Alumno.Entity;
			}
			set
			{
				Alumno previousValue = this._Alumno.Entity;
				if (((previousValue != value) 
							|| (this._Alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumno.Entity = null;
						previousValue.Asignacion.Remove(this);
					}
					this._Alumno.Entity = value;
					if ((value != null))
					{
						value.Asignacion.Add(this);
						this._codigo_alumno = value.codigo_alumno;
					}
					else
					{
						this._codigo_alumno = default(string);
					}
					this.SendPropertyChanged("Alumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesor_Curso_Asignacion", Storage="_Profesor_Curso", ThisKey="codigo_prof_curso", OtherKey="codigo_prof_curso", IsForeignKey=true)]
		public Profesor_Curso Profesor_Curso
		{
			get
			{
				return this._Profesor_Curso.Entity;
			}
			set
			{
				Profesor_Curso previousValue = this._Profesor_Curso.Entity;
				if (((previousValue != value) 
							|| (this._Profesor_Curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Profesor_Curso.Entity = null;
						previousValue.Asignacion.Remove(this);
					}
					this._Profesor_Curso.Entity = value;
					if ((value != null))
					{
						value.Asignacion.Add(this);
						this._codigo_prof_curso = value.codigo_prof_curso;
					}
					else
					{
						this._codigo_prof_curso = default(int);
					}
					this.SendPropertyChanged("Profesor_Curso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ciclo")]
	public partial class Ciclo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_ciclo;
		
		private string _nombre_ciclo;
		
		private bool _estado_ciclo;
		
		private EntitySet<Profesor_Curso> _Profesor_Curso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_cicloChanging(int value);
    partial void Oncodigo_cicloChanged();
    partial void Onnombre_cicloChanging(string value);
    partial void Onnombre_cicloChanged();
    partial void Onestado_cicloChanging(bool value);
    partial void Onestado_cicloChanged();
    #endregion
		
		public Ciclo()
		{
			this._Profesor_Curso = new EntitySet<Profesor_Curso>(new Action<Profesor_Curso>(this.attach_Profesor_Curso), new Action<Profesor_Curso>(this.detach_Profesor_Curso));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_ciclo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_ciclo
		{
			get
			{
				return this._codigo_ciclo;
			}
			set
			{
				if ((this._codigo_ciclo != value))
				{
					this.Oncodigo_cicloChanging(value);
					this.SendPropertyChanging();
					this._codigo_ciclo = value;
					this.SendPropertyChanged("codigo_ciclo");
					this.Oncodigo_cicloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_ciclo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nombre_ciclo
		{
			get
			{
				return this._nombre_ciclo;
			}
			set
			{
				if ((this._nombre_ciclo != value))
				{
					this.Onnombre_cicloChanging(value);
					this.SendPropertyChanging();
					this._nombre_ciclo = value;
					this.SendPropertyChanged("nombre_ciclo");
					this.Onnombre_cicloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_ciclo", DbType="Bit NOT NULL")]
		public bool estado_ciclo
		{
			get
			{
				return this._estado_ciclo;
			}
			set
			{
				if ((this._estado_ciclo != value))
				{
					this.Onestado_cicloChanging(value);
					this.SendPropertyChanging();
					this._estado_ciclo = value;
					this.SendPropertyChanged("estado_ciclo");
					this.Onestado_cicloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciclo_Profesor_Curso", Storage="_Profesor_Curso", ThisKey="codigo_ciclo", OtherKey="codigo_ciclo")]
		public EntitySet<Profesor_Curso> Profesor_Curso
		{
			get
			{
				return this._Profesor_Curso;
			}
			set
			{
				this._Profesor_Curso.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Profesor_Curso(Profesor_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Ciclo = this;
		}
		
		private void detach_Profesor_Curso(Profesor_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Ciclo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Curso")]
	public partial class Curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codigo_curso;
		
		private string _nombre_curso;
		
		private EntitySet<Profesor_Curso> _Profesor_Curso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_cursoChanging(string value);
    partial void Oncodigo_cursoChanged();
    partial void Onnombre_cursoChanging(string value);
    partial void Onnombre_cursoChanged();
    #endregion
		
		public Curso()
		{
			this._Profesor_Curso = new EntitySet<Profesor_Curso>(new Action<Profesor_Curso>(this.attach_Profesor_Curso), new Action<Profesor_Curso>(this.detach_Profesor_Curso));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_curso", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codigo_curso
		{
			get
			{
				return this._codigo_curso;
			}
			set
			{
				if ((this._codigo_curso != value))
				{
					this.Oncodigo_cursoChanging(value);
					this.SendPropertyChanging();
					this._codigo_curso = value;
					this.SendPropertyChanged("codigo_curso");
					this.Oncodigo_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_curso", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string nombre_curso
		{
			get
			{
				return this._nombre_curso;
			}
			set
			{
				if ((this._nombre_curso != value))
				{
					this.Onnombre_cursoChanging(value);
					this.SendPropertyChanging();
					this._nombre_curso = value;
					this.SendPropertyChanged("nombre_curso");
					this.Onnombre_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Profesor_Curso", Storage="_Profesor_Curso", ThisKey="codigo_curso", OtherKey="codigo_curso")]
		public EntitySet<Profesor_Curso> Profesor_Curso
		{
			get
			{
				return this._Profesor_Curso;
			}
			set
			{
				this._Profesor_Curso.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Profesor_Curso(Profesor_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Curso = this;
		}
		
		private void detach_Profesor_Curso(Profesor_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Curso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_depto;
		
		private string _nombre_depto;
		
		private EntitySet<Municipio> _Municipio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_deptoChanging(int value);
    partial void Oncod_deptoChanged();
    partial void Onnombre_deptoChanging(string value);
    partial void Onnombre_deptoChanged();
    #endregion
		
		public Departamento()
		{
			this._Municipio = new EntitySet<Municipio>(new Action<Municipio>(this.attach_Municipio), new Action<Municipio>(this.detach_Municipio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_depto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cod_depto
		{
			get
			{
				return this._cod_depto;
			}
			set
			{
				if ((this._cod_depto != value))
				{
					this.Oncod_deptoChanging(value);
					this.SendPropertyChanging();
					this._cod_depto = value;
					this.SendPropertyChanged("cod_depto");
					this.Oncod_deptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_depto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_depto
		{
			get
			{
				return this._nombre_depto;
			}
			set
			{
				if ((this._nombre_depto != value))
				{
					this.Onnombre_deptoChanging(value);
					this.SendPropertyChanging();
					this._nombre_depto = value;
					this.SendPropertyChanged("nombre_depto");
					this.Onnombre_deptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Municipio", Storage="_Municipio", ThisKey="cod_depto", OtherKey="cod_depto")]
		public EntitySet<Municipio> Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				this._Municipio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Municipio(Municipio entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Municipio(Municipio entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Municipio")]
	public partial class Municipio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_municipio;
		
		private string _nombre_municipio;
		
		private int _cod_depto;
		
		private EntitySet<Alumno> _Alumno;
		
		private EntitySet<Profesor> _Profesor;
		
		private EntityRef<Departamento> _Departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_municipioChanging(string value);
    partial void Oncod_municipioChanged();
    partial void Onnombre_municipioChanging(string value);
    partial void Onnombre_municipioChanged();
    partial void Oncod_deptoChanging(int value);
    partial void Oncod_deptoChanged();
    #endregion
		
		public Municipio()
		{
			this._Alumno = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno), new Action<Alumno>(this.detach_Alumno));
			this._Profesor = new EntitySet<Profesor>(new Action<Profesor>(this.attach_Profesor), new Action<Profesor>(this.detach_Profesor));
			this._Departamento = default(EntityRef<Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_municipio", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_municipio
		{
			get
			{
				return this._cod_municipio;
			}
			set
			{
				if ((this._cod_municipio != value))
				{
					this.Oncod_municipioChanging(value);
					this.SendPropertyChanging();
					this._cod_municipio = value;
					this.SendPropertyChanged("cod_municipio");
					this.Oncod_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_municipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_municipio
		{
			get
			{
				return this._nombre_municipio;
			}
			set
			{
				if ((this._nombre_municipio != value))
				{
					this.Onnombre_municipioChanging(value);
					this.SendPropertyChanging();
					this._nombre_municipio = value;
					this.SendPropertyChanged("nombre_municipio");
					this.Onnombre_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_depto", DbType="Int NOT NULL")]
		public int cod_depto
		{
			get
			{
				return this._cod_depto;
			}
			set
			{
				if ((this._cod_depto != value))
				{
					if (this._Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_deptoChanging(value);
					this.SendPropertyChanging();
					this._cod_depto = value;
					this.SendPropertyChanged("cod_depto");
					this.Oncod_deptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_Alumno", Storage="_Alumno", ThisKey="cod_municipio", OtherKey="cod_municipio")]
		public EntitySet<Alumno> Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				this._Alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_Profesor", Storage="_Profesor", ThisKey="cod_municipio", OtherKey="cod_municipio")]
		public EntitySet<Profesor> Profesor
		{
			get
			{
				return this._Profesor;
			}
			set
			{
				this._Profesor.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Municipio", Storage="_Departamento", ThisKey="cod_depto", OtherKey="cod_depto", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Municipio.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Municipio.Add(this);
						this._cod_depto = value.cod_depto;
					}
					else
					{
						this._cod_depto = default(int);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = this;
		}
		
		private void detach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = null;
		}
		
		private void attach_Profesor(Profesor entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = this;
		}
		
		private void detach_Profesor(Profesor entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profesor")]
	public partial class Profesor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _dpi_profesor;
		
		private string _nombres_profesor;
		
		private string _apellidos_profesor;
		
		private string _direccion_profesor;
		
		private string _telefono_profesor;
		
		private bool _estado_profesor;
		
		private string _usuario_profesor;
		
		private string _contrasenia;
		
		private string _cod_municipio;
		
		private EntitySet<Profesor_Curso> _Profesor_Curso;
		
		private EntityRef<Municipio> _Municipio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondpi_profesorChanging(string value);
    partial void Ondpi_profesorChanged();
    partial void Onnombres_profesorChanging(string value);
    partial void Onnombres_profesorChanged();
    partial void Onapellidos_profesorChanging(string value);
    partial void Onapellidos_profesorChanged();
    partial void Ondireccion_profesorChanging(string value);
    partial void Ondireccion_profesorChanged();
    partial void Ontelefono_profesorChanging(string value);
    partial void Ontelefono_profesorChanged();
    partial void Onestado_profesorChanging(bool value);
    partial void Onestado_profesorChanged();
    partial void Onusuario_profesorChanging(string value);
    partial void Onusuario_profesorChanged();
    partial void OncontraseniaChanging(string value);
    partial void OncontraseniaChanged();
    partial void Oncod_municipioChanging(string value);
    partial void Oncod_municipioChanged();
    #endregion
		
		public Profesor()
		{
			this._Profesor_Curso = new EntitySet<Profesor_Curso>(new Action<Profesor_Curso>(this.attach_Profesor_Curso), new Action<Profesor_Curso>(this.detach_Profesor_Curso));
			this._Municipio = default(EntityRef<Municipio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi_profesor", DbType="NVarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string dpi_profesor
		{
			get
			{
				return this._dpi_profesor;
			}
			set
			{
				if ((this._dpi_profesor != value))
				{
					this.Ondpi_profesorChanging(value);
					this.SendPropertyChanging();
					this._dpi_profesor = value;
					this.SendPropertyChanged("dpi_profesor");
					this.Ondpi_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres_profesor", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombres_profesor
		{
			get
			{
				return this._nombres_profesor;
			}
			set
			{
				if ((this._nombres_profesor != value))
				{
					this.Onnombres_profesorChanging(value);
					this.SendPropertyChanging();
					this._nombres_profesor = value;
					this.SendPropertyChanged("nombres_profesor");
					this.Onnombres_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos_profesor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string apellidos_profesor
		{
			get
			{
				return this._apellidos_profesor;
			}
			set
			{
				if ((this._apellidos_profesor != value))
				{
					this.Onapellidos_profesorChanging(value);
					this.SendPropertyChanging();
					this._apellidos_profesor = value;
					this.SendPropertyChanged("apellidos_profesor");
					this.Onapellidos_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_profesor", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion_profesor
		{
			get
			{
				return this._direccion_profesor;
			}
			set
			{
				if ((this._direccion_profesor != value))
				{
					this.Ondireccion_profesorChanging(value);
					this.SendPropertyChanging();
					this._direccion_profesor = value;
					this.SendPropertyChanged("direccion_profesor");
					this.Ondireccion_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_profesor", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string telefono_profesor
		{
			get
			{
				return this._telefono_profesor;
			}
			set
			{
				if ((this._telefono_profesor != value))
				{
					this.Ontelefono_profesorChanging(value);
					this.SendPropertyChanging();
					this._telefono_profesor = value;
					this.SendPropertyChanged("telefono_profesor");
					this.Ontelefono_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_profesor", DbType="Bit NOT NULL")]
		public bool estado_profesor
		{
			get
			{
				return this._estado_profesor;
			}
			set
			{
				if ((this._estado_profesor != value))
				{
					this.Onestado_profesorChanging(value);
					this.SendPropertyChanging();
					this._estado_profesor = value;
					this.SendPropertyChanged("estado_profesor");
					this.Onestado_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_profesor", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string usuario_profesor
		{
			get
			{
				return this._usuario_profesor;
			}
			set
			{
				if ((this._usuario_profesor != value))
				{
					this.Onusuario_profesorChanging(value);
					this.SendPropertyChanging();
					this._usuario_profesor = value;
					this.SendPropertyChanged("usuario_profesor");
					this.Onusuario_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenia", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string contrasenia
		{
			get
			{
				return this._contrasenia;
			}
			set
			{
				if ((this._contrasenia != value))
				{
					this.OncontraseniaChanging(value);
					this.SendPropertyChanging();
					this._contrasenia = value;
					this.SendPropertyChanged("contrasenia");
					this.OncontraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_municipio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cod_municipio
		{
			get
			{
				return this._cod_municipio;
			}
			set
			{
				if ((this._cod_municipio != value))
				{
					if (this._Municipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_municipioChanging(value);
					this.SendPropertyChanging();
					this._cod_municipio = value;
					this.SendPropertyChanged("cod_municipio");
					this.Oncod_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesor_Profesor_Curso", Storage="_Profesor_Curso", ThisKey="dpi_profesor", OtherKey="dpi_profesor")]
		public EntitySet<Profesor_Curso> Profesor_Curso
		{
			get
			{
				return this._Profesor_Curso;
			}
			set
			{
				this._Profesor_Curso.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_Profesor", Storage="_Municipio", ThisKey="cod_municipio", OtherKey="cod_municipio", IsForeignKey=true)]
		public Municipio Municipio
		{
			get
			{
				return this._Municipio.Entity;
			}
			set
			{
				Municipio previousValue = this._Municipio.Entity;
				if (((previousValue != value) 
							|| (this._Municipio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Municipio.Entity = null;
						previousValue.Profesor.Remove(this);
					}
					this._Municipio.Entity = value;
					if ((value != null))
					{
						value.Profesor.Add(this);
						this._cod_municipio = value.cod_municipio;
					}
					else
					{
						this._cod_municipio = default(string);
					}
					this.SendPropertyChanged("Municipio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Profesor_Curso(Profesor_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Profesor = this;
		}
		
		private void detach_Profesor_Curso(Profesor_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Profesor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profesor_Curso")]
	public partial class Profesor_Curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_prof_curso;
		
		private System.DateTime _fecha_asignacion;
		
		private int _codigo_ciclo;
		
		private string _dpi_profesor;
		
		private string _codigo_curso;
		
		private EntitySet<Asignacion> _Asignacion;
		
		private EntityRef<Curso> _Curso;
		
		private EntityRef<Ciclo> _Ciclo;
		
		private EntityRef<Profesor> _Profesor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_prof_cursoChanging(int value);
    partial void Oncodigo_prof_cursoChanged();
    partial void Onfecha_asignacionChanging(System.DateTime value);
    partial void Onfecha_asignacionChanged();
    partial void Oncodigo_cicloChanging(int value);
    partial void Oncodigo_cicloChanged();
    partial void Ondpi_profesorChanging(string value);
    partial void Ondpi_profesorChanged();
    partial void Oncodigo_cursoChanging(string value);
    partial void Oncodigo_cursoChanged();
    #endregion
		
		public Profesor_Curso()
		{
			this._Asignacion = new EntitySet<Asignacion>(new Action<Asignacion>(this.attach_Asignacion), new Action<Asignacion>(this.detach_Asignacion));
			this._Curso = default(EntityRef<Curso>);
			this._Ciclo = default(EntityRef<Ciclo>);
			this._Profesor = default(EntityRef<Profesor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_prof_curso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_prof_curso
		{
			get
			{
				return this._codigo_prof_curso;
			}
			set
			{
				if ((this._codigo_prof_curso != value))
				{
					this.Oncodigo_prof_cursoChanging(value);
					this.SendPropertyChanging();
					this._codigo_prof_curso = value;
					this.SendPropertyChanged("codigo_prof_curso");
					this.Oncodigo_prof_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_asignacion", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fecha_asignacion
		{
			get
			{
				return this._fecha_asignacion;
			}
			set
			{
				if ((this._fecha_asignacion != value))
				{
					this.Onfecha_asignacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_asignacion = value;
					this.SendPropertyChanged("fecha_asignacion");
					this.Onfecha_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_ciclo", DbType="Int NOT NULL")]
		public int codigo_ciclo
		{
			get
			{
				return this._codigo_ciclo;
			}
			set
			{
				if ((this._codigo_ciclo != value))
				{
					if (this._Ciclo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_cicloChanging(value);
					this.SendPropertyChanging();
					this._codigo_ciclo = value;
					this.SendPropertyChanged("codigo_ciclo");
					this.Oncodigo_cicloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi_profesor", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string dpi_profesor
		{
			get
			{
				return this._dpi_profesor;
			}
			set
			{
				if ((this._dpi_profesor != value))
				{
					if (this._Profesor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondpi_profesorChanging(value);
					this.SendPropertyChanging();
					this._dpi_profesor = value;
					this.SendPropertyChanged("dpi_profesor");
					this.Ondpi_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_curso", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string codigo_curso
		{
			get
			{
				return this._codigo_curso;
			}
			set
			{
				if ((this._codigo_curso != value))
				{
					if (this._Curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_cursoChanging(value);
					this.SendPropertyChanging();
					this._codigo_curso = value;
					this.SendPropertyChanged("codigo_curso");
					this.Oncodigo_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesor_Curso_Asignacion", Storage="_Asignacion", ThisKey="codigo_prof_curso", OtherKey="codigo_prof_curso")]
		public EntitySet<Asignacion> Asignacion
		{
			get
			{
				return this._Asignacion;
			}
			set
			{
				this._Asignacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Profesor_Curso", Storage="_Curso", ThisKey="codigo_curso", OtherKey="codigo_curso", IsForeignKey=true)]
		public Curso Curso
		{
			get
			{
				return this._Curso.Entity;
			}
			set
			{
				Curso previousValue = this._Curso.Entity;
				if (((previousValue != value) 
							|| (this._Curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Curso.Entity = null;
						previousValue.Profesor_Curso.Remove(this);
					}
					this._Curso.Entity = value;
					if ((value != null))
					{
						value.Profesor_Curso.Add(this);
						this._codigo_curso = value.codigo_curso;
					}
					else
					{
						this._codigo_curso = default(string);
					}
					this.SendPropertyChanged("Curso");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciclo_Profesor_Curso", Storage="_Ciclo", ThisKey="codigo_ciclo", OtherKey="codigo_ciclo", IsForeignKey=true)]
		public Ciclo Ciclo
		{
			get
			{
				return this._Ciclo.Entity;
			}
			set
			{
				Ciclo previousValue = this._Ciclo.Entity;
				if (((previousValue != value) 
							|| (this._Ciclo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ciclo.Entity = null;
						previousValue.Profesor_Curso.Remove(this);
					}
					this._Ciclo.Entity = value;
					if ((value != null))
					{
						value.Profesor_Curso.Add(this);
						this._codigo_ciclo = value.codigo_ciclo;
					}
					else
					{
						this._codigo_ciclo = default(int);
					}
					this.SendPropertyChanged("Ciclo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesor_Profesor_Curso", Storage="_Profesor", ThisKey="dpi_profesor", OtherKey="dpi_profesor", IsForeignKey=true)]
		public Profesor Profesor
		{
			get
			{
				return this._Profesor.Entity;
			}
			set
			{
				Profesor previousValue = this._Profesor.Entity;
				if (((previousValue != value) 
							|| (this._Profesor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Profesor.Entity = null;
						previousValue.Profesor_Curso.Remove(this);
					}
					this._Profesor.Entity = value;
					if ((value != null))
					{
						value.Profesor_Curso.Add(this);
						this._dpi_profesor = value.dpi_profesor;
					}
					else
					{
						this._dpi_profesor = default(string);
					}
					this.SendPropertyChanged("Profesor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asignacion(Asignacion entity)
		{
			this.SendPropertyChanging();
			entity.Profesor_Curso = this;
		}
		
		private void detach_Asignacion(Asignacion entity)
		{
			this.SendPropertyChanging();
			entity.Profesor_Curso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaAlumno")]
	public partial class VistaAlumno
	{
		
		private string _Codigo;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private System.DateTime _Fecha_Nacimiento;
		
		private string _Direccion;
		
		private string _Correo;
		
		private string _Telefono;
		
		private string _Usuario;
		
		private string _Contraseña;
		
		private int _Codigo_Departamento;
		
		private string _Departamento;
		
		private string _Codigo_Municipio;
		
		private string _Municipio;
		
		public VistaAlumno()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Nacimiento]", Storage="_Fecha_Nacimiento", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this._Fecha_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo Departamento]", Storage="_Codigo_Departamento", DbType="Int NOT NULL")]
		public int Codigo_Departamento
		{
			get
			{
				return this._Codigo_Departamento;
			}
			set
			{
				if ((this._Codigo_Departamento != value))
				{
					this._Codigo_Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo Municipio]", Storage="_Codigo_Municipio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Codigo_Municipio
		{
			get
			{
				return this._Codigo_Municipio;
			}
			set
			{
				if ((this._Codigo_Municipio != value))
				{
					this._Codigo_Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
